import {
  DropboxTransport,
  IndexedDBStore,
  Repository,
  SyncEngine,
  beginDropboxOAuth,
  completeDropboxOAuth,
  createRevisionCache,
  createBatch,
  debounce,
  exchangeDropboxRefreshToken,
  isOfflineError,
  openSlaktlandskapDB,
  registerKorpholmenServiceWorker,
  resolveDeviceId,
  validateOperation,
} from '../core/data-layer.js';
import { mergePersonReferences } from '../core/master-data.js';
import { ReadOnlyMaster } from '../core/read-only-master.js';
import { DROPBOX_CLIENT_ID, DROPBOX_SCOPES, LOCAL_BOOTSTRAP_URL } from './config.js';
import { KLASSER, KLASSSTANDARD_METHOD, klassnamn, standardklass, standardklassFranNamn } from './klassstandard.js';
import { parseRaceTime } from './time.js';

const $=selector=>document.querySelector(selector);
const app=$('#app');
const statusNode=$('#sync-status');
const connectButton=$('#connect-dropbox');
const bootstrapButton=$('#bootstrap-local');
const standardizeClassesButton=$('#standardize-classes');
const dialog=$('#result-dialog');
const isSourceTree=location.pathname.includes('/apps/korpholmenrunt/');
const TOKEN_META='dropbox:refresh-token';
const BOOTSTRAP_META='bootstrap:korpholmenrunt-2026-08-04-v2';
const ui={view:'oversikt',search:'',year:'alla',className:'alla',course:'alla',profile:null,duelA:'',duelB:'',sortKey:'year',sortDirection:'desc',splitReview:false};
let store;let repository;let matrikelMaster;let accessToken=null;let accessTokenExpiresAt=0;let syncPromise=null;
const viewCache=createRevisionCache(()=>`${repository?.revision||0}:${matrikelMaster?.revision||0}`);

const escapeHtml=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const escapeAttribute=escapeHtml;
const normalize=value=>String(value||'').normalize('NFD').replace(/\p{Diacritic}/gu,'').toLocaleLowerCase('sv').replace(/[^a-z0-9]+/g,' ').trim();
const recordList=type=>viewCache(`records:${type}`,()=>repository?repository.listEntities(type).map(entity=>({id:entity.entity_id,...entity.fields})):[]);
const results=()=>viewCache('results',()=>[...recordList('race-result')].sort((a,b)=>b.year-a.year||(a.duration_seconds??Infinity)-(b.duration_seconds??Infinity)));
const editions=()=>viewCache('editions',()=>[...recordList('race-edition')].sort((a,b)=>a.year-b.year));
const storedPeople=()=>recordList('person-ref');
const people=()=>viewCache('people',()=>mergePersonReferences(storedPeople(),matrikelMaster).sort((a,b)=>a.display_name.localeCompare(b.display_name,'sv')));
const boats=()=>viewCache('boats',()=>[...recordList('boat-ref')].sort((a,b)=>a.name.localeCompare(b.name,'sv')));
const personLinks=()=>recordList('race-person-link');
const participantPlaceholders=()=>recordList('race-participant-placeholder');
const peopleMap=()=>viewCache('people-map',()=>new Map(people().map(item=>[item.external_id,item])));
const boatsMap=()=>viewCache('boats-map',()=>new Map(boats().map(item=>[item.external_id,item])));
const participantPlaceholdersMap=()=>viewCache('placeholder-map',()=>new Map(participantPlaceholders().map(item=>[item.id,item])));
const linksByResult=()=>viewCache('links-by-result',()=>{const map=new Map();for(const link of personLinks()){if(!map.has(link.result_id))map.set(link.result_id,[]);map.get(link.result_id).push(link)}return map});
const validTime=result=>Number.isInteger(result.duration_seconds)&&result.duration_seconds>=0;
const reviewPending=result=>['utkast','oklar','granskning krävs'].includes(result.review_status);
const rankEligible=result=>validTime(result)&&(result.time_status||'tolkad')==='tolkad'&&!reviewPending(result);
const timeLabel=result=>result.time_raw||'—';
const courseLabel=code=>code?`${code}-banan`:'Okänd bana';

function setStatus(text,tone=''){statusNode.textContent=text;statusNode.className=tone?`status-${tone}`:''}
const deviceId=()=>resolveDeviceId({store,key:'korpholmen:runt-device-id',prefix:'runt-web-'});
function redirectUri(){return new URL(isSourceTree?'../../':'../',location.href).href}
const className=klassnamn;
const classChoices=()=>KLASSER.map(klass=>klass.name);
const classHasManualOverride=(result,rawClass)=>{if(result.class_match_status!=='manuell'||!result.class_match_method||result.class_match_method===KLASSSTANDARD_METHOD)return false;const selected=standardklass(result.class_name);return !selected||selected.id!==rawClass.id};
function classStandardizationPlan(){return results().flatMap(result=>{const klass=standardklass(result.class_raw);if(!klass||classHasManualOverride(result,klass))return [];const expected={class_id:klass.id,class_name:klass.name,class_match_status:'manuell',class_match_method:KLASSSTANDARD_METHOD};const entries=Object.entries(expected).filter(([field,value])=>result[field]!==value).map(([field,value])=>({entityType:'race-result',entityId:result.id,field,value}));return entries.length?[{result,klass,entries}]:[]})}

function rankMap(){
  const groups=new Map();
  for(const result of results().filter(rankEligible)){const key=`${result.year}|${result.course_code}|${result.class_name}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(result)}
  const ranks=new Map();
  for(const group of groups.values()){group.sort((a,b)=>a.duration_seconds-b.duration_seconds);let rank=0;let last=null;group.forEach((result,index)=>{if(result.duration_seconds!==last)rank=index+1;last=result.duration_seconds;ranks.set(result.id,{rank,total:group.length})})}
  return ranks;
}

const participantRawValues=result=>Array.isArray(result?.participants_raw)?result.participants_raw:[];
function resultSearchText(result,linkMap,pMap,bMap,placeholderMap){return viewCache(`result-search:${result.id}`,()=>{const linked=(linkMap.get(result.id)||[]).map(link=>pMap.get(link.person_id)?.display_name||placeholderMap.get(link.placeholder_id)?.label||link.raw_name);return normalize([result.year,result.boat_name_raw,bMap.get(result.boat_id)?.name,...participantRawValues(result),result.class_name,result.time_raw,...linked].join(' '))})}
function filteredResults(){const linkMap=linksByResult();const pMap=peopleMap();const bMap=boatsMap();const placeholderMap=participantPlaceholdersMap();const refs=[...pMap.values()];const query=normalize(ui.search);return results().filter(result=>(ui.year==='alla'||String(result.year)===ui.year)&&(ui.className==='alla'||result.class_name===ui.className)&&(ui.course==='alla'||result.course_code===ui.course)&&(!ui.splitReview||(linkMap.get(result.id)||[]).some(link=>participantMayBeMerged(link,refs)))&&(!query||resultSearchText(result,linkMap,pMap,bMap,placeholderMap).includes(query)))}
function participantLabel(result){return participantRawValues(result).filter(participantValuePresent).join(' · ')||'Deltagare saknas'}
const participantRole=()=> 'Tävlande';
const participantValuePresent=value=>Boolean(String(value||'').trim())&&!['-','.'].includes(String(value).trim());
const personLinkConnected=link=>Boolean(link?.person_id)&&['kopplad','manuell'].includes(link.match_status);
const participantPlaceholderConnected=link=>link?.participant_kind==='placeholder'&&Boolean(link?.placeholder_id)&&link.confirmed===true;
const reviewDecisionResolved=item=>item?.confirmed===true&&item?.review_decision==='bevarad okopplad';
const participantLinkResolved=link=>personLinkConnected(link)||participantPlaceholderConnected(link)||reviewDecisionResolved(link);
const boatLinkConnected=result=>Boolean(result?.boat_id)&&['kopplad','manuell','ny farkost'].includes(result.boat_match_status);
const boatReviewResolved=result=>boatLinkConnected(result)||reviewDecisionResolved(result);
const svCollator=new Intl.Collator('sv',{numeric:true,sensitivity:'base'});
function structuredChoices(items,labelField,idField){const counts=new Map();for(const item of items){const label=String(item[labelField]||'').trim();counts.set(label,(counts.get(label)||0)+1)}return items.map(item=>{const base=String(item[labelField]||'').trim();const id=item[idField];return {id,base,label:counts.get(base)>1?`${base} · ${id}`:base,item}})}
function choiceOptions(choices){return choices.map(choice=>`<option value="${escapeAttribute(choice.label)}"></option>`).join('')}
function resolveChoice(value,choices){const exact=choices.find(choice=>choice.label===value);if(exact)return exact;const normalized=normalize(value);const matches=choices.filter(choice=>normalize(choice.base)===normalized);return matches.length===1?matches[0]:null}
function inlineChoice({list,placeholder,label,attributes}){return `<input class="snabbval" type="search" list="${escapeAttribute(list)}" placeholder="${escapeAttribute(placeholder)}" aria-label="${escapeAttribute(label)}" autocomplete="off" data-action="inline-edit" ${attributes}>`}
function splitParticipantSortNames(value){const raw=String(value||'').trim();if(!participantValuePresent(raw))return [];const parts=raw.split(/\s*(?:,|&|\+|\boch\b)\s*/iu).filter(participantValuePresent);return parts.length>1?parts:[raw]}
function participantSplitOptions(value){const raw=String(value||'').trim();if(!participantValuePresent(raw))return [];const explicit=raw.split(/\s*(?:,|&|\+|\boch\b)\s*/iu).filter(participantValuePresent);if(explicit.length>1)return [explicit];const words=raw.split(/\s+/u).filter(participantValuePresent);if(words.length<2||words.length>8)return [];const options=[words];for(let index=1;index<words.length;index+=1)options.push([words.slice(0,index).join(' '),words.slice(index).join(' ')]);const unique=new Map();for(const parts of options)unique.set(parts.map(normalize).join('|'),parts);return [...unique.values()]}
function participantMayBeMerged(link,refs=people()){if(!link||participantLinkResolved(link)||link.split_root_link_id)return false;const raw=String(link.raw_name||'').trim();if(!participantSplitOptions(raw).length||/\bm\s*fl\b|\bbarn\b/iu.test(raw))return false;if(/,|&|\+|\boch\b/iu.test(raw))return true;const normalized=normalize(raw);if(refs.some(person=>normalize(person.display_name)===normalized))return false;const words=normalized.split(' ');const firstNames=new Set(refs.map(person=>normalize(person.display_name).split(' ')[0]).filter(Boolean));const surnames=new Set(refs.flatMap(person=>{const parts=normalize(person.display_name).split(' ');return parts.length>1?[parts.at(-1)]:[]}));return words.filter(word=>firstNames.has(word)).length>1||(link.match_method==='namndelar'&&!surnames.has(words.at(-1)))||(words.length>2&&!surnames.has(words.at(-1)))}
function participantOrderValue(link){return Number.isInteger(link?.participant_order)?link.participant_order:900}
function participantGroupValue(link){return Number.isInteger(link?.participant_group)?link.participant_group:0}
function orderedParticipantLinks(list){return [...list].sort((a,b)=>participantOrderValue(a)-participantOrderValue(b)||String(a.id).localeCompare(String(b.id),'sv'))}
function participantSourceNote(link){const source=String(link.source_raw_name||'').trim();return source&&normalize(source)!==normalize(link.raw_name)?`<small class="registerkalla delningskalla">Källrad före delning: ${escapeHtml(source)}</small>`:''}
function participantSplitControls(link,editable){if(!editable||participantLinkResolved(link))return '';const options=participantSplitOptions(link.raw_name);if(!options.length)return '';return `<details class="namndelning"><summary data-action="toggle-split-details">Dela namn…</summary><small>Välj var en person slutar och nästa börjar. Källraden bevaras.</small><div class="delningsval">${options.map(parts=>`<button type="button" data-action="split-participant" data-link-id="${escapeAttribute(link.id)}" data-split-parts="${escapeAttribute(JSON.stringify(parts))}">${parts.map(escapeHtml).join(' <b aria-hidden="true">|</b> ')}</button>`).join('')}</div></details>`}
function participantSortEntries(result,linkMap,pMap){const entries=[];const seenGroups=new Set();const placeholderMap=participantPlaceholdersMap();for(const link of orderedParticipantLinks(linkMap.get(result.id)||[])){const registered=pMap.get(link.person_id);const placeholder=placeholderMap.get(link.placeholder_id);const names=registered?[registered.display_name]:placeholder?[placeholder.label]:splitParticipantSortNames(link.raw_name);const participantGroup=participantGroupValue(link);for(const name of names)entries.push({name,participantGroup,role:participantRole(),linkId:link.id});if(names.length)seenGroups.add(participantGroup)}participantRawValues(result).forEach((raw,participantGroup)=>{if(seenGroups.has(participantGroup))return;for(const name of splitParticipantSortNames(raw))entries.push({name,participantGroup,role:participantRole(),linkId:null})});return entries}
function resultSortValue(result,key,{ranks,bMap}){if(key==='year')return result.year;if(key==='course')return result.course_code||null;if(key==='time')return validTime(result)?result.duration_seconds:null;if(key==='placement')return ranks.get(result.id)?.rank??null;if(key==='boat')return bMap.get(result.boat_id)?.name||result.boat_name_raw||null;if(key==='class')return result.class_name||null;return `${reviewPending(result)?'preliminär':'granskad'} ${result.boat_match_status||''} ${result.time_status||''}`}
function sortResults(list,context){const direction=ui.sortDirection==='asc'?1:-1;return [...list].sort((left,right)=>{const a=resultSortValue(left,ui.sortKey,context);const b=resultSortValue(right,ui.sortKey,context);if(a==null&&b==null)return 0;if(a==null)return 1;if(b==null)return -1;const comparison=typeof a==='number'&&typeof b==='number'?a-b:svCollator.compare(String(a),String(b));return comparison*direction||right.year-left.year||(left.duration_seconds??Infinity)-(right.duration_seconds??Infinity)})}
function sortResultRows(list,context){if(ui.sortKey!=='participants')return sortResults(list,context).map(result=>({result,sortParticipant:null}));const direction=ui.sortDirection==='asc'?1:-1;const rows=list.flatMap(result=>{const participants=participantSortEntries(result,context.linkMap,context.pMap);return participants.length?participants.map(sortParticipant=>({result,sortParticipant})):[{result,sortParticipant:null}]});return rows.sort((left,right)=>{const a=left.sortParticipant?.name||null;const b=right.sortParticipant?.name||null;if(a==null&&b==null)return right.result.year-left.result.year;if(a==null)return 1;if(b==null)return -1;return svCollator.compare(a,b)*direction||right.result.year-left.result.year||(left.result.duration_seconds??Infinity)-(right.result.duration_seconds??Infinity)})}
function sortHeader(key,label,title=''){const active=ui.sortKey===key;const direction=active?ui.sortDirection:null;return `<th aria-sort="${active?(direction==='asc'?'ascending':'descending'):'none'}"><button class="sortknapp" type="button" data-action="sort-results" data-sort-key="${escapeAttribute(key)}"${title?` title="${escapeAttribute(title)}"`:''}>${escapeHtml(label)}<span aria-hidden="true">${active?(direction==='asc'?'▲':'▼'):'↕'}</span></button></th>`}
function registerAnchor(ref,label){return ref?.url?`<a class="registernamn" data-action="open-register" href="${escapeAttribute(ref.url)}">${escapeHtml(label)}</a>`:`<strong class="registernamn">${escapeHtml(label)}</strong>`}
function boatCandidateControls(candidates,result,editable){if(!candidates.length)return '';const choices=editable?candidates.map(candidate=>`<span class="forslagsval"><button class="forslagsknapp" type="button" data-action="quick-confirm-boat" data-result-id="${escapeAttribute(result.id)}" data-boat-id="${escapeAttribute(candidate.external_id)}" title="Bekräfta ${escapeAttribute(candidate.name)}">✓ ${escapeHtml(candidate.name)}</button>${candidate.url?`<a class="forslagsgranska" data-action="open-register" href="${escapeAttribute(candidate.url)}" aria-label="Granska ${escapeAttribute(candidate.name)} i Båtregistret" title="Öppna i Båtregistret">↗</a>`:''}</span>`).join(''):candidates.map(candidate=>registerAnchor(candidate,candidate.name)).join(', ');return `<div class="registerforslag"><small class="registerkalla">Förslag i Båtregistret:</small><div class="forslagsrad">${choices}</div></div>`}
function personCandidateControls(candidates,link,editable){if(!candidates.length)return '';const choices=editable?candidates.map(candidate=>`<span class="forslagsval"><button class="forslagsknapp" type="button" data-action="quick-confirm-person" data-link-id="${escapeAttribute(link.id)}" data-person-id="${escapeAttribute(candidate.external_id)}" title="Bekräfta ${escapeAttribute(candidate.display_name)}">✓ ${escapeHtml(candidate.display_name)}</button>${candidate.url?`<a class="forslagsgranska" data-action="open-register" href="${escapeAttribute(candidate.url)}" aria-label="Granska ${escapeAttribute(candidate.display_name)} i Matrikeln" title="Öppna i Matrikeln">↗</a>`:''}</span>`).join(''):candidates.map(candidate=>registerAnchor(candidate,candidate.display_name)).join(', ');return `<div class="registerforslag"><small class="registerkalla">Förslag i Matrikeln:</small><div class="forslagsrad">${choices}</div></div>`}
function boatRegisterCell(result,bMap,editable=false){
  const registered=bMap.get(result.boat_id);const raw=result.boat_name_raw||'Okänd båt';
  const chooser=editable?inlineChoice({list:'inline-boat-options',placeholder:registered?'Sök och byt båt…':'Sök och koppla båt…',label:`Båt för resultat ${result.year}`,attributes:`data-inline-boat-result="${escapeAttribute(result.id)}"`}):'';
  if(registered&&boatLinkConnected(result))return `<div class="registerpost"><div class="registerhuvud">${registerAnchor(registered,registered.name)}<span class="registeretikett">Båtregistret</span></div>${registered.name!==result.boat_name_raw&&result.boat_name_raw?`<small class="registerkalla">Källnamn: ${escapeHtml(result.boat_name_raw)}</small>`:''}${chooser}</div>`;
  const candidates=(result.boat_candidate_ids||[]).map(id=>bMap.get(id)).filter(Boolean).slice(0,3);
  return `<div class="registerpost"><div class="registerhuvud"><strong class="registernamn">${escapeHtml(raw)}</strong><span class="registeretikett saknas">Ej kopplad</span></div>${boatCandidateControls(candidates,result,editable)}${chooser}</div>`;
}
function participantRegisterCell(result,linkMap,pMap,editable=false){
  const links=orderedParticipantLinks(linkMap.get(result.id)||[]);
  const placeholderMap=participantPlaceholdersMap();
  const chooser=(participantGroup,linkId)=>editable?inlineChoice({list:'inline-person-options',placeholder:'Sök och koppla person…',label:'Tävlande: koppla till Matrikeln',attributes:`data-inline-person-result="${escapeAttribute(result.id)}" data-inline-person-group="${participantGroup}" data-inline-person-link="${escapeAttribute(linkId)}"`}):'';
  if(!links.length){const raw=participantRawValues(result).map((name,participantGroup)=>({name,participantGroup})).filter(item=>participantValuePresent(item.name));return raw.length?`<div class="registerlista">${raw.map(({name,participantGroup})=>{const linkId=`race-person-link:${result.id.replace(/^race-result:/,'')}-participant-${participantGroup+1}`;return `<div class="registerpost"><small class="registerroll">Tävlande</small><div class="registerhuvud"><strong class="registernamn">${escapeHtml(name)}</strong><span class="registeretikett saknas">Ej kopplad</span></div>${chooser(participantGroup,linkId)}</div>`}).join('')}</div>`:'<span class="registersaknas">Deltagare saknas</span>'}
  return `<div class="registerlista">${links.map(link=>{const registered=pMap.get(link.person_id);const placeholder=placeholderMap.get(link.placeholder_id);const raw=link.raw_name||'Okänd deltagare';const choice=participantPlaceholderConnected(link)?'':chooser(participantGroupValue(link),link.id);const sourceNote=participantSourceNote(link);if(placeholder&&participantPlaceholderConnected(link))return `<div class="registerpost"><small class="registerroll">Tävlande</small><div class="registerhuvud"><strong class="registernamn">${escapeHtml(placeholder.label)}</strong><span class="registeretikett platshallare">Strukturerad platshållare</span></div><small class="registerkalla">Okända ytterligare tävlande · avslutad fråga</small>${sourceNote}</div>`;if(registered&&personLinkConnected(link))return `<div class="registerpost"><small class="registerroll">Tävlande</small><div class="registerhuvud">${registerAnchor(registered,registered.display_name)}<span class="registeretikett">Matrikeln</span></div>${registered.display_name!==link.raw_name&&link.raw_name?`<small class="registerkalla">Källnamn: ${escapeHtml(link.raw_name)}</small>`:''}${sourceNote}${choice}</div>`;const candidates=(link.candidate_ids||[]).map(id=>pMap.get(id)).filter(Boolean).slice(0,3);return `<div class="registerpost"><small class="registerroll">Tävlande</small><div class="registerhuvud"><strong class="registernamn">${escapeHtml(raw)}</strong><span class="registeretikett saknas">Ej kopplad</span></div>${sourceNote}${personCandidateControls(candidates,link,editable)}${participantSplitControls(link,editable)}${choice}</div>`}).join('')}</div>`;
}
function unmatchedCount(){return results().filter(reviewPending).length+personLinks().filter(link=>!participantLinkResolved(link)).length+results().filter(result=>!boatReviewResolved(result)).length}
function updateFilters(){
  const current={year:$('#year-filter').value,className:$('#class-filter').value,course:$('#course-filter').value};
  const yearValues=editions().map(item=>item.year).sort((a,b)=>b-a);const classValues=[...new Set([...classChoices(),...results().map(item=>item.class_name)])].sort((a,b)=>a.localeCompare(b,'sv'));const courseValues=[...new Set(results().map(item=>item.course_code).filter(Boolean))].sort();
  $('#year-filter').innerHTML='<option value="alla">Alla år</option>'+yearValues.map(value=>`<option value="${value}">${value}</option>`).join('');
  $('#class-filter').innerHTML='<option value="alla">Alla klasser</option>'+classValues.map(value=>`<option value="${escapeAttribute(value)}">${escapeHtml(value)}</option>`).join('');
  $('#course-filter').innerHTML='<option value="alla">Alla banor</option>'+courseValues.map(value=>`<option value="${escapeAttribute(value)}">${escapeHtml(courseLabel(value))}</option>`).join('');
  $('#year-filter').value=yearValues.includes(Number(current.year))?current.year:'alla';$('#class-filter').value=classValues.includes(current.className)?current.className:'alla';$('#course-filter').value=courseValues.includes(current.course)?current.course:'alla';
  ui.year=$('#year-filter').value;ui.className=$('#class-filter').value;ui.course=$('#course-filter').value;
  $('#edit-boat-id').innerHTML='<option value="">Inte kopplad</option>'+boats().map(boat=>`<option value="${escapeAttribute(boat.external_id)}">${escapeHtml(boat.name)}</option>`).join('');
  const personOptions='<option value="">Inte kopplad</option>'+people().map(person=>`<option value="${escapeAttribute(person.external_id)}">${escapeHtml(person.display_name)}</option>`).join('');for(const id of ['edit-person-1-id','edit-person-2-id','edit-person-3-id'])$(`#${id}`).innerHTML=personOptions;
  $('#review-count').textContent=String(unmatchedCount());
  const pendingClasses=classStandardizationPlan().length;standardizeClassesButton.hidden=pendingClasses===0;standardizeClassesButton.textContent=`Tillämpa klassstandard${pendingClasses?` (${pendingClasses})`:''}`;
}

function emptyState(){return `<section class="tomt"><span>◎</span><h2>Mastern väntar på första synken</h2><p>Anslut Dropbox för den levande databasen.${isSourceTree?' Du kan också aktivera den reproducerbara startmastern här på localhost.':''}</p></section>`}
function recordCard(result,title){if(!result)return '';return `<article class="rekordkort"><div><p class="overrad">${escapeHtml(title)}</p><div class="tid">${escapeHtml(timeLabel(result))}</div><h3>${escapeHtml(result.boat_name_raw||'Okänd båt')}</h3><p>${escapeHtml(participantLabel(result))}<br>${result.year} · ${escapeHtml(result.class_name)} · ${escapeHtml(courseLabel(result.course_code))}</p></div><button class="lankknapp" data-result-id="${escapeAttribute(result.id)}">Visa resultatet →</button></article>`}

function renderOverview(){
  const all=results();if(!all.length)return emptyState();
  const years=editions();const fastestS=all.filter(item=>item.course_code==='S'&&rankEligible(item)).sort((a,b)=>a.duration_seconds-b.duration_seconds)[0];const fastestL=all.filter(item=>item.course_code==='L'&&rankEligible(item)).sort((a,b)=>a.duration_seconds-b.duration_seconds)[0];
  const maxYear=Math.max(...years.map(item=>item.result_count));const classCounts=[...all.reduce((map,item)=>map.set(item.class_name,(map.get(item.class_name)||0)+1),new Map())].sort((a,b)=>b[1]-a[1]);const maxClass=classCounts[0]?.[1]||1;
  const busiest=[...years].sort((a,b)=>b.result_count-a.result_count)[0];const boatCounts=[...all.filter(item=>item.boat_id).reduce((map,item)=>map.set(item.boat_id,(map.get(item.boat_id)||0)+1),new Map())].sort((a,b)=>b[1]-a[1]);const topBoat=boatsMap().get(boatCounts[0]?.[0]);
  return `<section class="hero"><article class="herokort"><p class="overrad">Den levande resultatboken</p><h2>En ö. Många sätt att ta sig runt.</h2><p>Hela den registrerade tävlingshistorien korslänkad med människor och båtar—sökbar, redigerbar och byggd för nästa sommar.</p><div class="herosiffror"><div><strong>${all.length}</strong><span>resultat</span></div><div><strong>${years.length}</strong><span>tävlingsår</span></div><div><strong>${new Set(all.map(item=>item.boat_id||normalize(item.boat_name_raw))).size}</strong><span>båtidentiteter</span></div></div></article>${recordCard(fastestS,'Snabbast registrerad · S')}</section><section class="panelgrid"><article class="panel span8"><p class="overrad">Deltagande över tid</p><h2>Startfältet år för år</h2><div class="arstaplar">${years.map(item=>`<button class="arstapel" style="height:${Math.max(8,item.result_count/maxYear*100)}%" data-year="${item.year}" data-tip="${item.year}: ${item.result_count}"></button>`).join('')}</div></article><article class="panel span4"><p class="overrad">Farkosterna</p><h2>Klassernas avtryck</h2><div class="klasslista">${classCounts.slice(0,8).map(([name,count])=>`<div class="klassrad"><span>${escapeHtml(name)}</span><div class="klassbar"><i style="width:${count/maxClass*100}%"></i></div><b>${count}</b></div>`).join('')}</div></article><article class="panel span7"><p class="overrad">Det databasen berättar</p><h2>Tre snabba fynd</h2><div class="insikter"><div class="insikt"><strong>${busiest.year} samlade det största fältet</strong><span>${busiest.result_count} registrerade starter.</span></div><div class="insikt"><strong>${escapeHtml(topBoat?.name||'En återkommande båt')} bär kontinuiteten</strong><span>${boatCounts[0]?.[1]||0} kopplade starter i materialet.</span></div><div class="insikt"><strong>${unmatchedCount()} kopplingar väntar på ett mänskligt beslut</strong><span>Rånamnen är bevarade tills rätt person eller båt har bekräftats.</span></div></div></article><div class="span5">${recordCard(fastestL,'Snabbast registrerad · L')}</div></section>`;
}

function renderResults(){
  const ranks=rankMap();const bMap=boatsMap();const pMap=peopleMap();const linkMap=linksByResult();const context={ranks,bMap,pMap,linkMap};const refs=[...pMap.values()];const suspected=results().filter(result=>(linkMap.get(result.id)||[]).some(link=>participantMayBeMerged(link,refs))).length;const filtered=filteredResults();const rows=sortResultRows(filtered,context);const personMode=ui.sortKey==='participants';const personChoices=structuredChoices(refs,'display_name','external_id');const boatChoices=structuredChoices([...bMap.values()],'name','external_id');const classes=classChoices();
  return `<header class="sidtitel"><div><h2>Alla resultat</h2><p>${personMode?`${rows.length} tävlandeposter från ${filtered.length} av ${results().length} resultat. Varje tävlande får en egen alfabetisk rad; samma resultat kan därför förekomma flera gånger.`:`${filtered.length} av ${results().length} poster.`} Klicka på en rubrik för att sortera. Sökfälten i raden sparar register- och klassval direkt.</p><button type="button" class="delningsfilter ${ui.splitReview?'aktiv':''}" data-action="toggle-split-review" aria-pressed="${ui.splitReview}">${ui.splitReview?'Visa alla resultat':'Granska möjliga sammanslagningar'} <b>${suspected}</b></button></div></header><div class="tabellskal"><table class="resultattabell"><thead><tr>${sortHeader('year','År')}${sortHeader('course','Bana')}${sortHeader('time','Tid')}${sortHeader('placement','Plac.')}${sortHeader('boat','Båt / register')}${sortHeader('participants','Tävlande / register','Visar en alfabetisk rad per tävlande')}${sortHeader('class','Klass')}${sortHeader('status','Status')}</tr></thead><tbody>${rows.map(({result,sortParticipant})=>{const rank=ranks.get(result.id);return `<tr data-result-id="${escapeAttribute(result.id)}" class="${reviewPending(result)?'preliminar-rad':''}"><td>${result.year}</td><td><span class="badge ${String(result.course_code).toLowerCase()}">${escapeHtml(result.course_code||'—')}</span></td><td class="tidcell">${escapeHtml(timeLabel(result))}</td><td>${rank?`${rank.rank}/${rank.total}`:'—'}</td><td>${boatRegisterCell(result,bMap,true)}</td><td>${sortParticipant?`<div class="sorteringsperson">Sorteringsnamn: <strong>${escapeHtml(sortParticipant.name)}</strong></div>`:''}${participantRegisterCell(result,linkMap,pMap,true)}</td><td><div class="registerpost"><strong class="registernamn">${escapeHtml(result.class_name)}</strong>${result.class_raw&&result.class_raw!==result.class_name?`<small class="registerkalla">Källklass: ${escapeHtml(result.class_raw)}</small>`:''}${inlineChoice({list:'inline-class-options',placeholder:'Sök och byt klass…',label:`Klass för resultat ${result.year}`,attributes:`data-inline-class-result="${escapeAttribute(result.id)}"`})}</div></td><td>${reviewPending(result)?'<span class="badge utkast">Preliminär</span>':`<span class="${['kopplad','manuell','ny farkost'].includes(result.boat_match_status)?'kopplad':'olost'}">${escapeHtml(result.boat_match_status)}</span>`}${result.time_status!=='tolkad'?` · <span class="badge osaker">${escapeHtml(result.time_status)}</span>`:''}</td></tr>`}).join('')}</tbody></table></div><datalist id="inline-person-options">${choiceOptions(personChoices)}</datalist><datalist id="inline-boat-options">${choiceOptions(boatChoices)}</datalist><datalist id="inline-class-options">${classes.map(value=>`<option value="${escapeAttribute(value)}"></option>`).join('')}</datalist>`;
}

function topList(course,limit=15){return results().filter(item=>item.course_code===course&&rankEligible(item)).sort((a,b)=>a.duration_seconds-b.duration_seconds).slice(0,limit)}
function topListHtml(title,list){const bMap=boatsMap();const pMap=peopleMap();const linkMap=linksByResult();return `<article class="topplista"><p class="overrad">${escapeHtml(title)}</p><h3>All time</h3>${list.map((result,index)=>`<div class="topprad" data-result-id="${escapeAttribute(result.id)}"><span class="plac">${index+1}</span><span class="topptid">${escapeHtml(timeLabel(result))}</span><div class="topregister">${boatRegisterCell(result,bMap)}${participantRegisterCell(result,linkMap,pMap)}</div><small>${result.year} · ${escapeHtml(result.class_name)}</small></div>`).join('')}</article>`}
function renderRecords(){
  if(!results().length)return emptyState();
  const classRecords=[...new Set(results().map(item=>item.class_name))].sort((a,b)=>a.localeCompare(b,'sv')).map(name=>results().filter(item=>item.course_code==='S'&&item.class_name===name&&rankEligible(item)).sort((a,b)=>a.duration_seconds-b.duration_seconds)[0]).filter(Boolean);
  const bMap=boatsMap();const pMap=peopleMap();const linkMap=linksByResult();
  return `<header class="sidtitel"><div><h2>Rekordkabinettet</h2><p>S- och L-banan hålls isär. Osäkra och ogiltiga tider räknas inte som rekord.</p></div></header><section class="rekordgrid">${topListHtml('S-banan',topList('S'))}${topListHtml('L-banan',topList('L'))}<article class="topplista span12"><p class="overrad">Klassrekord · S-banan</p><h3>Snabbast i varje gren</h3>${classRecords.map((result,index)=>`<div class="topprad" data-result-id="${escapeAttribute(result.id)}"><span class="plac">${index+1}</span><span class="topptid">${escapeHtml(timeLabel(result))}</span><div class="topregister"><strong>${escapeHtml(result.class_name)}</strong>${boatRegisterCell(result,bMap)}${participantRegisterCell(result,linkMap,pMap)}</div><small>${result.year}</small></div>`).join('')}</article></section>`;
}

function profileCatalog(){
  const rank=rankMap();const links=personLinks();const pMap=peopleMap();const bMap=boatsMap();const all=results();const catalog=[];
  const resultMap=new Map(all.map(item=>[item.id,item]));const personResultIds=new Map();for(const link of links.filter(item=>item.person_id)){if(!personResultIds.has(link.person_id))personResultIds.set(link.person_id,new Set());personResultIds.get(link.person_id).add(link.result_id)}
  for(const [id,ids] of personResultIds){const items=[...ids].map(resultId=>resultMap.get(resultId)).filter(Boolean);const ref=pMap.get(id);if(!ref)continue;catalog.push({key:`person:${id}`,type:'person',id,name:ref.display_name,url:ref.url,items,starts:items.length,wins:items.filter(item=>rank.get(item.id)?.rank===1).length,best:items.filter(item=>item.course_code==='S'&&rankEligible(item)).sort((a,b)=>a.duration_seconds-b.duration_seconds)[0]})}
  const boatResults=new Map();for(const result of all.filter(item=>item.boat_id)){if(!boatResults.has(result.boat_id))boatResults.set(result.boat_id,[]);boatResults.get(result.boat_id).push(result)}
  for(const [id,items] of boatResults){const ref=bMap.get(id);if(!ref)continue;catalog.push({key:`boat:${id}`,type:'boat',id,name:ref.name,url:ref.url,items,starts:items.length,wins:items.filter(item=>rank.get(item.id)?.rank===1).length,best:items.filter(item=>item.course_code==='S'&&rankEligible(item)).sort((a,b)=>a.duration_seconds-b.duration_seconds)[0]})}
  return catalog.sort((a,b)=>b.starts-a.starts||a.name.localeCompare(b.name,'sv'));
}
function profileCard(profile){return `<button class="profilkort" data-profile="${escapeAttribute(profile.key)}"><h3>${escapeHtml(profile.name)}</h3><p>${profile.type==='person'?'Matrikeln':'Båtregistret'} · ${profile.items.length?`${Math.min(...profile.items.map(item=>item.year))}–${Math.max(...profile.items.map(item=>item.year))}`:'—'}</p><div class="profilfakta"><div><strong>${profile.starts}</strong><span>starter</span></div><div><strong>${profile.wins}</strong><span>klassegrar</span></div><div><strong>${profile.best?escapeHtml(profile.best.time_raw):'—'}</strong><span>bästa S</span></div></div></button>`}
function renderProfileDetail(profile){const rank=rankMap();const bMap=boatsMap();const pMap=peopleMap();const linkMap=linksByResult();return `<header class="sidtitel"><div><button class="lankknapp" data-action="back-profiles">← Alla profiler</button><h2>${escapeHtml(profile.name)}</h2><p>${profile.type==='person'?'Deltagare kopplad till Matrikeln':'Båt kopplad till Båtregistret'}.</p></div></header><article class="profilvy"><aside class="profilhuvud"><p class="overrad">${profile.type==='person'?'Personprofil':'Båtprofil'}</p><h3>${escapeHtml(profile.name)}</h3><div class="profilfakta"><div><strong>${profile.starts}</strong><span>starter</span></div><div><strong>${profile.wins}</strong><span>klassegrar</span></div></div>${profile.url?`<p><a data-action="open-register" href="${escapeAttribute(profile.url)}">Öppna i ${profile.type==='person'?'Matrikeln':'Båtregistret'} ↗</a></p>`:''}</aside><div><table class="resultattabell"><thead><tr><th>År</th><th>Tid</th><th>Plac.</th><th>Båt / register</th><th>Tävlande / register</th><th>Klass</th></tr></thead><tbody>${profile.items.sort((a,b)=>b.year-a.year).map(result=>{const placement=rank.get(result.id);return `<tr data-result-id="${escapeAttribute(result.id)}"><td>${result.year}</td><td class="tidcell">${escapeHtml(result.time_raw)}</td><td>${placement?`${placement.rank}/${placement.total}`:'—'}</td><td>${boatRegisterCell(result,bMap)}</td><td>${participantRegisterCell(result,linkMap,pMap)}</td><td>${escapeHtml(result.class_name)} · ${escapeHtml(result.course_code)}</td></tr>`}).join('')}</tbody></table></div></article>`}
function renderProfiles(){const catalog=profileCatalog();if(ui.profile){const profile=catalog.find(item=>item.key===ui.profile);if(profile)return renderProfileDetail(profile);ui.profile=null}const persons=catalog.filter(item=>item.type==='person').slice(0,60);const vessel=catalog.filter(item=>item.type==='boat').slice(0,60);return `<header class="sidtitel"><div><h2>Människor & båtar</h2><p>Profilerna använder stabila register-ID:n. Entydiga förnamn visas som förslag men ligger kvar i matchningskön tills de har bekräftats.</p></div></header><section class="panel span12"><p class="overrad">Deltagare</p><h2>Mest aktiva</h2><div class="profilgrid">${persons.map(profileCard).join('')}</div></section><section class="panel span12" style="margin-top:22px"><p class="overrad">Båtar</p><h2>Flitigast runt ön</h2><div class="profilgrid">${vessel.map(profileCard).join('')}</div></section>`}

function duelOption(profile){return `<option value="${escapeAttribute(profile.key)}">${profile.type==='person'?'Person':'Båt'} · ${escapeHtml(profile.name)}</option>`}
function renderDuel(){const catalog=profileCatalog();if(!ui.duelA)ui.duelA=catalog[0]?.key||'';if(!ui.duelB)ui.duelB=catalog[1]?.key||'';const a=catalog.find(item=>item.key===ui.duelA);const b=catalog.find(item=>item.key===ui.duelB);const common=a&&b?a.items.filter(left=>b.items.some(right=>left.year===right.year&&left.course_code===right.course_code&&left.class_name===right.class_name)).length:0;return `<header class="sidtitel"><div><h2>Öduellen</h2><p>Ställ två deltagare eller båtar mot varandra genom hela resultathistorien.</p></div></header><div class="duellval"><label><span>Utmanare A</span><select id="duel-a">${catalog.map(duelOption).join('')}</select></label><div class="mot">mot</div><label><span>Utmanare B</span><select id="duel-b">${catalog.map(duelOption).join('')}</select></label></div>${a&&b?`<article class="duellkort"><div class="duellsida"><h3>${escapeHtml(a.name)}</h3><p><span class="duellsiffra">${a.starts}</span><br>starter</p><p>${a.wins} klassegrar · bästa S ${a.best?escapeHtml(a.best.time_raw):'—'}</p></div><div class="duellmitt"><span>${common}<br><small>jämförbara möten</small></span></div><div class="duellsida"><h3>${escapeHtml(b.name)}</h3><p><span class="duellsiffra">${b.starts}</span><br>starter</p><p>${b.wins} klassegrar · bästa S ${b.best?escapeHtml(b.best.time_raw):'—'}</p></div></article>`:emptyState()}`}

function matchContext(result,bMap){if(!result)return '<div class="matchkontext"><p class="matchuppgift"><span>Båt</span><strong>Okänd båt</strong></p><p class="matchuppgift"><span>Tävlande</span><strong>Deltagare saknas</strong></p></div>';const registeredBoat=bMap.get(result.boat_id);const boatName=registeredBoat?.name||result.boat_name_raw||'Okänd båt';const sourceBoat=registeredBoat&&result.boat_name_raw&&registeredBoat.name!==result.boat_name_raw?`<small class="matchkallnamn">Källnamn: ${escapeHtml(result.boat_name_raw)}</small>`:'';const participants=participantRawValues(result).filter(participantValuePresent).map(name=>`<span class="matchperson"><small>Tävlande</small>${escapeHtml(name)}</span>`).join('')||'<strong>Deltagare saknas</strong>';return `<div class="matchkontext"><p class="matchuppgift"><span>Båt</span><strong>${escapeHtml(boatName)}</strong>${sourceBoat}</p><div class="matchuppgift"><span>Tävlande</span><div class="matchdeltagare">${participants}</div></div></div>`}
function candidateOptions(ids,refs,labelField,idField,noun,current=''){return `<option value="">Välj ${noun}…</option>`+ids.map(id=>refs.find(item=>item[idField]===id)).filter(Boolean).map(item=>`<option value="${escapeAttribute(item[idField])}"${item[idField]===current?' selected':''}>${escapeHtml(item[labelField])}</option>`).join('')}
function reviewIssueList(result){const issues=Array.isArray(result.review_issues)?result.review_issues.filter(Boolean):[];return issues.length?`<ul class="granskningspunkter">${issues.map(issue=>`<li>${escapeHtml(issue)}</li>`).join('')}</ul>`:'<p class="inga-punkter">Ingen särskild fråga angiven — kontrollera raden mot källan.</p>'}
function renderMatching(){
  const pRefs=people();const bRefs=boats();const bMap=new Map(bRefs.map(item=>[item.external_id,item]));const resultMap=new Map(results().map(item=>[item.id,item]));
  const draftResults=results().filter(reviewPending);const unresolvedPeople=personLinks().filter(link=>!participantLinkResolved(link));const unresolvedBoats=results().filter(result=>!boatReviewResolved(result));
  return `<header class="sidtitel"><div><h2>Granska & matcha</h2><p>Kontrollera preliminära källrader och koppla därefter stabila identiteter utan att skriva över originalvärdena.</p></div></header>
  <section class="panel span12"><p class="overrad">Resultatrader · ${draftResults.length}</p><h2>Vad behöver kontrolleras?</h2><div class="matchgrid">${draftResults.slice(0,100).map(result=>`<article class="matchkort granskningskort"><p>${result.year} · ${escapeHtml(result.course_code||'okänd bana')} · ${escapeHtml(result.class_name||'okänd klass')}</p><h3>${escapeHtml(timeLabel(result))} · ${escapeHtml(participantLabel(result))}</h3>${matchContext(result,bMap)}${reviewIssueList(result)}<div class="statusrad"><button class="sekundar" data-action="open-result" data-result-id="${escapeAttribute(result.id)}">Öppna och rätta</button><button data-action="approve-result" data-result-id="${escapeAttribute(result.id)}">Godkänn raden</button></div></article>`).join('')||'<p>Alla publicerade resultatrader är granskade.</p>'}</div></section>
  <section class="panel span12" style="margin-top:22px"><p class="overrad">Personer · ${unresolvedPeople.length}</p><h2>Vem är vem?</h2><div class="matchgrid">${unresolvedPeople.slice(0,100).map(link=>{const result=resultMap.get(link.result_id);return `<article class="matchkort"><p>${escapeHtml(participantRole(link))} · ${escapeHtml(result?.year||'')}</p><h3>${escapeHtml(link.raw_name)}</h3>${participantSourceNote(link)}${matchContext(result,bMap)}${participantSplitControls(link,true)}<select data-person-select="${escapeAttribute(link.id)}">${candidateOptions(link.candidate_ids?.length?link.candidate_ids:pRefs.map(item=>item.external_id),pRefs,'display_name','external_id','person',link.person_id)}</select><div class="statusrad"><span class="badge osaker">${escapeHtml(link.match_status)}</span><button class="sekundar" data-action="keep-person-unlinked" data-link-id="${escapeAttribute(link.id)}">Bevara utan koppling</button><button data-action="confirm-person" data-link-id="${escapeAttribute(link.id)}">Koppla</button></div></article>`}).join('')||'<p>Alla deltagarnamn är avgjorda.</p>'}</div></section>
  <section class="panel span12" style="margin-top:22px"><p class="overrad">Båtar · ${unresolvedBoats.length}</p><h2>Vilken båt är det?</h2><div class="matchgrid">${unresolvedBoats.slice(0,100).map(result=>`<article class="matchkort"><p>${result.year} · ${escapeHtml(result.class_name)}</p><h3>${escapeHtml(result.boat_name_raw||'Okänd båt')}</h3>${matchContext(result,bMap)}<select data-boat-select="${escapeAttribute(result.id)}">${candidateOptions(result.boat_candidate_ids?.length?result.boat_candidate_ids:bRefs.map(item=>item.external_id),bRefs,'name','external_id','båt',result.boat_id)}</select><div class="statusrad"><span class="badge osaker">${escapeHtml(result.boat_match_status)}</span><button class="sekundar" data-action="keep-boat-unlinked" data-result-id="${escapeAttribute(result.id)}">Bevara utan koppling</button><button data-action="confirm-boat" data-result-id="${escapeAttribute(result.id)}">Koppla</button></div></article>`).join('')||'<p>Alla båtnamn är avgjorda.</p>'}</div></section>`
}

function render(){
  updateFilters();document.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('aktiv',button.dataset.view===ui.view));
  app.innerHTML=ui.view==='oversikt'?renderOverview():ui.view==='resultat'?renderResults():ui.view==='rekord'?renderRecords():ui.view==='profiler'?renderProfiles():ui.view==='duell'?renderDuel():renderMatching();
  $('#clear-search').hidden=!ui.search;
  if(ui.view==='duell'){$('#duel-a').value=ui.duelA;$('#duel-b').value=ui.duelB}
}

function openResultDialog(id=null){const result=id?results().find(item=>item.id===id):null;const raws=participantRawValues(result);const resultLinks=new Map((result?linksByResult().get(result.id)||[]:[]).map(link=>[participantGroupValue(link),link]));$('#dialog-title').textContent=result?'Granska resultat':'Nytt resultat';$('#result-id').value=result?.id||'';$('#edit-year').value=result?.year||new Date().getFullYear();$('#edit-course').value=result?.course_code||'';$('#edit-time').value=result?.time_raw||'';$('#edit-class').value=result?.class_raw||'';$('#edit-review-status').value=!result||reviewPending(result)?'granskning krävs':'granskad';$('#edit-review-issues').value=(result?.review_issues||[]).join('\n');$('#edit-boat-raw').value=result?.boat_name_raw||'';$('#edit-boat-id').value=result?.boat_id||'';$('#edit-participant-1').value=raws[0]||'';$('#edit-participant-2').value=raws[1]||'';$('#edit-participant-3').value=raws[2]||'';$('#edit-person-1-id').value=personLinkConnected(resultLinks.get(0))?resultLinks.get(0).person_id:'';$('#edit-person-2-id').value=personLinkConnected(resultLinks.get(1))?resultLinks.get(1).person_id:'';$('#edit-person-3-id').value=personLinkConnected(resultLinks.get(2))?resultLinks.get(2).person_id:'';$('#edit-participant-3-group').hidden=!participantValuePresent(raws[2]);$('#edit-notes').value=result?.notes||'';dialog.showModal()}
function clientPersonMatch(raw){const value=normalize(raw);if(!value)return {status:'saknas',person_id:null,candidates:[]};const refs=people();const exact=refs.filter(item=>normalize(item.display_name)===value);if(exact.length===1)return {status:'kopplad',person_id:exact[0].external_id,candidates:[exact[0].external_id]};if(!value.includes(' ')){const first=refs.filter(item=>normalize(item.display_name).split(' ')[0]===value);if(first.length===1)return {status:'föreslagen',person_id:first[0].external_id,candidates:[first[0].external_id]};if(first.length)return {status:'föreslagen',person_id:null,candidates:first.map(item=>item.external_id)}}return {status:'saknas',person_id:null,candidates:[]}}
function clientBoatMatch(raw,selected){if(selected)return {status:'manuell',boat_id:selected,candidates:[selected]};const value=normalize(raw).replace(/ /g,'');const candidates=boats().filter(item=>normalize(item.name).replace(/ /g,'')===value);return candidates.length===1?{status:'kopplad',boat_id:candidates[0].external_id,candidates:[candidates[0].external_id]}:{status:candidates.length?'föreslagen':'saknas',boat_id:null,candidates:candidates.map(item=>item.external_id)}}
async function saveResult(){
  const existing=$('#result-id').value;const prior=existing?results().find(item=>item.id===existing):null;const id=existing||`race-result:user-${crypto.randomUUID()}`;const time=parseRaceTime($('#edit-time').value);const boat=clientBoatMatch($('#edit-boat-raw').value,$('#edit-boat-id').value);const reviewStatus=$('#edit-review-status').value;const reviewIssues=$('#edit-review-issues').value.split('\n').map(value=>value.trim()).filter(Boolean);const participantData=[[0,$('#edit-participant-1').value,$('#edit-person-1-id').value],[1,$('#edit-participant-2').value,$('#edit-person-2-id').value],[2,$('#edit-participant-3').value,$('#edit-person-3-id').value]];const linkIds=[];const entries=[];const deletions=[];const allLinks=personLinks();const resultLinks=allLinks.filter(link=>link.result_id===id);let hasSplitParticipants=false;let participantOrder=0;
  if(!prior)for(const [field,value] of Object.entries({label:'Manuellt kompletterad i appen',source_type:'Appinmatning',source_table:null,sha256:null,original_path:null,private_copy:null,imported_on:new Date().toISOString().slice(0,10),row_count:null}))entries.push({entityType:'race-source',entityId:'race-source:user',field,value});
  for(const [participantGroup,raw,selectedPersonId] of participantData){const groupLinks=orderedParticipantLinks(resultLinks.filter(link=>participantGroupValue(link)===participantGroup));const preservesSplit=participantValuePresent(raw)&&groupLinks.length>1&&groupLinks.every(link=>normalize(link.source_raw_name)===normalize(raw.trim()));if(preservesSplit){for(const splitLink of groupLinks){linkIds.push(splitLink.id);entries.push({entityType:'race-person-link',entityId:splitLink.id,field:'participant_order',value:participantOrder},{entityType:'race-person-link',entityId:splitLink.id,field:'role',value:'tävlande'},{entityType:'race-person-link',entityId:splitLink.id,field:'participant_group',value:participantGroup});participantOrder+=1}hasSplitParticipants=true;continue}if(!participantValuePresent(raw)){deletions.push(...groupLinks.map(link=>({entityType:'race-person-link',entityId:link.id})));continue}const previous=groupLinks.length===1?groupLinks[0]:null;const linkId=previous?.id||`race-person-link:${id.replace(/^race-result:/,'')}-participant-${participantGroup+1}`;if(groupLinks.length>1)deletions.push(...groupLinks.map(link=>({entityType:'race-person-link',entityId:link.id})));const preservesPlaceholder=participantPlaceholderConnected(previous)&&(normalize(previous.source_raw_name)===normalize(raw.trim())||/^(?:m\s*\.?\s*fl\.?|med\s+flera)$/iu.test(raw.trim()));if(preservesPlaceholder){linkIds.push(linkId);entries.push({entityType:'race-person-link',entityId:linkId,field:'participant_order',value:participantOrder},{entityType:'race-person-link',entityId:linkId,field:'participant_group',value:participantGroup},{entityType:'race-person-link',entityId:linkId,field:'role',value:'tävlande'});participantOrder+=1;hasSplitParticipants=true;continue}const unchanged=previous?.raw_name===raw.trim();const clearedExisting=personLinkConnected(previous)&&!selectedPersonId;const match=selectedPersonId?{person_id:selectedPersonId,status:'manuell',method:'valt i resultatdialogen',candidates:[selectedPersonId],confirmed:true}:clearedExisting?{person_id:null,status:'saknas',method:'bortkopplad i resultatdialogen',candidates:[],confirmed:false}:unchanged?{person_id:previous.person_id,status:previous.match_status,method:previous.match_method,candidates:previous.candidate_ids||[],confirmed:previous.confirmed}:clientPersonMatch(raw);linkIds.push(linkId);for(const [name,value] of Object.entries({result_id:id,role:'tävlande',participant_group:participantGroup,participant_order:participantOrder,raw_name:raw.trim(),source_raw_name:null,participant_kind:'person',placeholder_id:null,split_from_link_id:null,split_root_link_id:null,person_id:match.person_id,match_status:match.status,match_method:match.method||(unchanged?'oförändrad':'redigerad i appen'),candidate_ids:match.candidates,confirmed:match.confirmed??match.status==='kopplad'}))entries.push({entityType:'race-person-link',entityId:linkId,field:name,value});participantOrder+=1}
  const participantsRaw=participantData.map(([,raw])=>raw.trim());const rawClass=$('#edit-class').value.trim();const klass=standardklass(rawClass);const fields={source_row_id:prior?.source_row_id??null,source_id:prior?.source_id??'race-source:user',year:Number($('#edit-year').value),boat_name_raw:$('#edit-boat-raw').value.trim(),boat_id:boat.boat_id,boat_match_status:boat.status,boat_match_method:'redigerad i appen',boat_candidate_ids:boat.candidates,participants_raw:participantsRaw,class_raw:rawClass,class_id:klass?.id??null,class_name:className(rawClass),class_match_status:klass?'manuell':'saknas',class_match_method:klass?'valt i resultatdialogen':'ingen standardträff',course_code:$('#edit-course').value,time_raw:$('#edit-time').value.trim(),duration_seconds:time.seconds,time_status:time.status,participant_link_ids:linkIds,participant_structure_status:hasSplitParticipants?'manuellt delad':null,notes:$('#edit-notes').value.trim(),review_status:reviewStatus,review_issues:reviewStatus==='granskad'?[]:reviewIssues,reviewed_by:reviewStatus==='granskad'?'Simon':null,reviewed_at:reviewStatus==='granskad'?new Date().toISOString():null,raw_row:prior?.raw_row??null};
  for(const [field,value] of Object.entries(fields))entries.push({entityType:'race-result',entityId:id,field,value});
  await repository.upsertFields(entries);if(deletions.length)await repository.deleteEntities(deletions);dialog.close();render();setStatus('Sparat lokalt · synkas automatiskt','ok');syncNow().catch(()=>{});
}
async function splitParticipantLink(linkId,parts){const link=personLinks().find(item=>item.id===linkId);const cleanParts=(Array.isArray(parts)?parts:[]).map(part=>String(part||'').trim()).filter(participantValuePresent);if(!link||cleanParts.length<2||cleanParts.length>8)throw new Error('Välj minst två giltiga namn');const result=results().find(item=>item.id===link.result_id);if(!result)throw new Error('Resultatraden kunde inte hittas');const current=orderedParticipantLinks(personLinks().filter(item=>item.result_id===result.id));const position=current.findIndex(item=>item.id===link.id);if(position<0)throw new Error('Namnraden kunde inte hittas');const sourceRaw=link.source_raw_name||link.raw_name;const participantGroup=participantGroupValue(link);const children=cleanParts.map(rawName=>({id:`race-person-link:user-split-${crypto.randomUUID()}`,rawName,match:clientPersonMatch(rawName)}));const finalLinks=[...current.slice(0,position),...children,...current.slice(position+1)];const entries=[];finalLinks.forEach((item,participantOrder)=>{if(item.rawName){const fields={result_id:result.id,role:'tävlande',participant_group:participantGroup,participant_order:participantOrder,raw_name:item.rawName,source_raw_name:sourceRaw,split_from_link_id:link.id,split_root_link_id:link.split_root_link_id||link.id,participant_kind:'person',person_id:item.match.person_id,match_status:item.match.status,match_method:'delad i resultatlistan',candidate_ids:item.match.candidates,confirmed:item.match.status==='kopplad'};for(const [field,value] of Object.entries(fields))entries.push({entityType:'race-person-link',entityId:item.id,field,value})}else{entries.push({entityType:'race-person-link',entityId:item.id,field:'participant_order',value:participantOrder},{entityType:'race-person-link',entityId:item.id,field:'role',value:'tävlande'})}});entries.push({entityType:'race-result',entityId:result.id,field:'participant_link_ids',value:finalLinks.map(item=>item.id)},{entityType:'race-result',entityId:result.id,field:'participant_structure_status',value:'manuellt delad'});await repository.setFields(entries);await repository.deleteEntities([{entityType:'race-person-link',entityId:link.id}]);render();setStatus(`${sourceRaw} delades till ${cleanParts.length} tävlande · källraden är bevarad · synkas automatiskt`,'ok');syncNow().catch(()=>{})}
async function confirmPersonCandidate(linkId,personId){const person=peopleMap().get(personId);const link=personLinks().find(item=>item.id===linkId);if(!person||!link)return;const result=results().find(item=>item.id===link.result_id);const entries=[{entityType:'race-person-link',entityId:linkId,field:'person_id',value:personId},{entityType:'race-person-link',entityId:linkId,field:'match_status',value:'manuell'},{entityType:'race-person-link',entityId:linkId,field:'match_method',value:'bekräftat från förslag i resultatlistan'},{entityType:'race-person-link',entityId:linkId,field:'confirmed',value:true},{entityType:'race-person-link',entityId:linkId,field:'review_decision',value:null},{entityType:'race-person-link',entityId:linkId,field:'candidate_ids',value:[personId]}];if(result)entries.push({entityType:'race-result',entityId:result.id,field:'participant_link_ids',value:[...new Set([...(result.participant_link_ids||[]),linkId])]});await repository.setFields(entries);render();setStatus(`${person.display_name} bekräftad i Matrikeln · synkas automatiskt`,'ok');syncNow().catch(()=>{})}
async function confirmBoatCandidate(resultId,boatId){const boat=boatsMap().get(boatId);if(!boat||!results().some(item=>item.id===resultId))return;await repository.setFields([{entityType:'race-result',entityId:resultId,field:'boat_id',value:boatId},{entityType:'race-result',entityId:resultId,field:'boat_match_status',value:'manuell'},{entityType:'race-result',entityId:resultId,field:'boat_match_method',value:'bekräftat från förslag i resultatlistan'},{entityType:'race-result',entityId:resultId,field:'review_decision',value:null},{entityType:'race-result',entityId:resultId,field:'boat_candidate_ids',value:[boatId]}]);render();setStatus(`${boat.name} bekräftad i Båtregistret · synkas automatiskt`,'ok');syncNow().catch(()=>{})}
async function keepPersonUnlinked(linkId){const link=personLinks().find(item=>item.id===linkId);if(!link)return;const reviewedAt=new Date().toISOString();await repository.setFields([{entityType:'race-person-link',entityId:linkId,field:'person_id',value:null},{entityType:'race-person-link',entityId:linkId,field:'match_status',value:'bevarad okopplad'},{entityType:'race-person-link',entityId:linkId,field:'match_method',value:'manuellt beslut: ingen säker registeridentitet'},{entityType:'race-person-link',entityId:linkId,field:'confirmed',value:true},{entityType:'race-person-link',entityId:linkId,field:'review_decision',value:'bevarad okopplad'},{entityType:'race-person-link',entityId:linkId,field:'reviewed_by',value:'Simon'},{entityType:'race-person-link',entityId:linkId,field:'reviewed_at',value:reviewedAt}]);render();setStatus(`${link.raw_name} bevarad utan registerkoppling · synkas automatiskt`,'ok');syncNow().catch(()=>{})}
async function keepBoatUnlinked(resultId){const result=results().find(item=>item.id===resultId);if(!result)return;const reviewedAt=new Date().toISOString();await repository.setFields([{entityType:'race-result',entityId:resultId,field:'boat_id',value:null},{entityType:'race-result',entityId:resultId,field:'boat_match_status',value:'bevarad okopplad'},{entityType:'race-result',entityId:resultId,field:'boat_match_method',value:'manuellt beslut: ingen säker registeridentitet'},{entityType:'race-result',entityId:resultId,field:'confirmed',value:true},{entityType:'race-result',entityId:resultId,field:'review_decision',value:'bevarad okopplad'},{entityType:'race-result',entityId:resultId,field:'reviewed_by',value:'Simon'},{entityType:'race-result',entityId:resultId,field:'reviewed_at',value:reviewedAt}]);render();setStatus(`${result.boat_name_raw||'Båtnamnet'} bevarat utan registerkoppling · synkas automatiskt`,'ok');syncNow().catch(()=>{})}
async function confirmPerson(linkId){const select=document.querySelector(`[data-person-select="${CSS.escape(linkId)}"]`);if(select?.value)await confirmPersonCandidate(linkId,select.value)}
async function confirmBoat(resultId){const select=document.querySelector(`[data-boat-select="${CSS.escape(resultId)}"]`);if(select?.value)await confirmBoatCandidate(resultId,select.value)}
async function updateInlineBoat(input){const choice=resolveChoice(input.value,structuredChoices(boats(),'name','external_id'));if(!choice){setStatus('Välj en båt ur Båtregistrets förslagslista','warning');return}const resultId=input.dataset.inlineBoatResult;await repository.setFields([{entityType:'race-result',entityId:resultId,field:'boat_id',value:choice.id},{entityType:'race-result',entityId:resultId,field:'boat_match_status',value:'manuell'},{entityType:'race-result',entityId:resultId,field:'boat_match_method',value:'valt direkt i resultatlistan'},{entityType:'race-result',entityId:resultId,field:'boat_candidate_ids',value:[choice.id]}]);render();setStatus(`${choice.base} kopplad från Båtregistret · synkas automatiskt`,'ok');syncNow().catch(()=>{})}
async function updateInlinePerson(input){const choice=resolveChoice(input.value,structuredChoices(people(),'display_name','external_id'));if(!choice){setStatus('Välj en person ur Matrikelns förslagslista','warning');return}const result=results().find(item=>item.id===input.dataset.inlinePersonResult);if(!result)return;const participantGroup=Number(input.dataset.inlinePersonGroup);const linkId=input.dataset.inlinePersonLink;const existingLink=personLinks().find(item=>item.id===linkId);const rawName=existingLink?.raw_name||participantRawValues(result)[participantGroup]||'';const linkIds=[...new Set([...(result.participant_link_ids||[]),linkId])];const fields={result_id:result.id,role:'tävlande',participant_group:participantGroup,participant_order:existingLink?.participant_order??personLinks().filter(item=>item.result_id===result.id).length,raw_name:rawName,participant_kind:'person',person_id:choice.id,match_status:'manuell',match_method:'valt direkt i resultatlistan',candidate_ids:[choice.id],confirmed:true};const entries=Object.entries(fields).map(([field,value])=>({entityType:'race-person-link',entityId:linkId,field,value}));entries.push({entityType:'race-result',entityId:result.id,field:'participant_link_ids',value:linkIds});await repository.upsertFields(entries);render();setStatus(`${choice.base} kopplad från Matrikeln · synkas automatiskt`,'ok');syncNow().catch(()=>{})}
async function updateInlineClass(input){const klass=standardklassFranNamn(input.value);if(!klass){setStatus('Välj en klass ur förslagslistan','warning');return}const resultId=input.dataset.inlineClassResult;await repository.setFields([{entityType:'race-result',entityId:resultId,field:'class_id',value:klass.id},{entityType:'race-result',entityId:resultId,field:'class_name',value:klass.name},{entityType:'race-result',entityId:resultId,field:'class_match_status',value:'manuell'},{entityType:'race-result',entityId:resultId,field:'class_match_method',value:'valt direkt i resultatlistan'}]);render();setStatus(`${klass.name} vald · källans klassvärde är bevarat · synkas automatiskt`,'ok');syncNow().catch(()=>{})}
function inlineTargetReady(input){if(input.matches('[data-inline-boat-result]'))return Boolean(resolveChoice(input.value,structuredChoices(boats(),'name','external_id')));if(input.matches('[data-inline-person-result]'))return Boolean(resolveChoice(input.value,structuredChoices(people(),'display_name','external_id')));if(input.matches('[data-inline-class-result]'))return Boolean(standardklassFranNamn(input.value));return false}
function runInlineUpdate(input,force=false){if(!input.matches('[data-inline-boat-result],[data-inline-person-result],[data-inline-class-result]')||input.dataset.inlineSaving==='true')return;if(!force&&!inlineTargetReady(input))return;input.dataset.inlineSaving='true';const task=input.matches('[data-inline-boat-result]')?updateInlineBoat(input):input.matches('[data-inline-person-result]')?updateInlinePerson(input):updateInlineClass(input);task.catch(error=>setStatus(error.message,'error')).finally(()=>{if(input.isConnected)delete input.dataset.inlineSaving})}
async function applyClassStandard(){const plan=classStandardizationPlan();if(!plan.length){setStatus('Klassstandarden är redan tillämpad','ok');return}standardizeClassesButton.disabled=true;setStatus(`Standardiserar ${plan.length} klassvärden…`);await repository.setFields(plan.flatMap(item=>item.entries));render();setStatus(`${plan.length} klassvärden standardiserade · källvärdena är bevarade · synkar…`,'ok');try{await syncNow()}finally{standardizeClassesButton.disabled=false}}
async function approveResult(resultId){const result=results().find(item=>item.id===resultId);const fields=[{entityType:'race-result',entityId:resultId,field:'review_status',value:'granskad'},{entityType:'race-result',entityId:resultId,field:'review_issues',value:[]},{entityType:'race-result',entityId:resultId,field:'reviewed_by',value:'Simon'},{entityType:'race-result',entityId:resultId,field:'reviewed_at',value:new Date().toISOString()}];if(validTime(result))fields.push({entityType:'race-result',entityId:resultId,field:'time_status',value:'tolkad'});await repository.setFields(fields);render();setStatus('Raden markerad som granskad · synkas automatiskt','ok');syncNow().catch(()=>{})}

function exportCsv(){const headers=['id','år','bana','tid','sekunder','klass-id','klass','klass rå','båt rå','båt-id','tävlande','matchstatus','granskningsstatus','granskningspunkter','anteckning'];const quote=value=>`"${String(value??'').replaceAll('"','""')}"`;const rows=filteredResults().map(item=>[item.id,item.year,item.course_code,item.time_raw,item.duration_seconds,item.class_id,item.class_name,item.class_raw,item.boat_name_raw,item.boat_id,participantRawValues(item).filter(participantValuePresent).join(' | '),item.boat_match_status,item.review_status,(item.review_issues||[]).join(' | '),item.notes]);const blob=new Blob([[headers,...rows].map(row=>row.map(quote).join(',')).join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`korpholmenrunt-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url)}

async function registerServiceWorker(){try{return await registerKorpholmenServiceWorker({sourceTree:isSourceTree})}catch(error){console.warn('Appskalet kunde inte uppdateras',error);return null}}
async function completeOAuthCallbackIfNeeded(){const url=new URL(location.href);if(!url.searchParams.has('code')&&!url.searchParams.has('error'))return;const token=await completeDropboxOAuth();accessToken=token.access_token;accessTokenExpiresAt=Date.now()+Math.max(30,Number(token.expires_in||0)-60)*1000;if(token.refresh_token)await store.putMeta(TOKEN_META,token.refresh_token);for(const parameter of ['code','state','error','error_description'])url.searchParams.delete(parameter);history.replaceState({},'',`${url.pathname}${url.search}${url.hash}`)}
async function currentAccessToken(){if(accessToken&&Date.now()<accessTokenExpiresAt)return accessToken;const refreshToken=await store.getMeta(TOKEN_META);if(!refreshToken||!DROPBOX_CLIENT_ID||navigator.onLine===false)return null;const token=await exchangeDropboxRefreshToken({clientId:DROPBOX_CLIENT_ID,refreshToken});accessToken=token.access_token;accessTokenExpiresAt=Date.now()+Math.max(30,Number(token.expires_in||0)-60)*1000;if(token.refresh_token&&token.refresh_token!==refreshToken)await store.putMeta(TOKEN_META,token.refresh_token);return accessToken}
async function uploadBootstrapOps(transport){const pending=await store.getMeta(BOOTSTRAP_META);if(!pending?.pending)return 0;const deviceIds=new Set(pending.device_ids||[pending.device_id]);const operations=(await store.getAllOps()).filter(operation=>deviceIds.has(operation.device_id));const byDevice=new Map();for(const operation of operations){if(!byDevice.has(operation.device_id))byDevice.set(operation.device_id,[]);byDevice.get(operation.device_id).push(operation)}let uploaded=0;for(const deviceOperations of byDevice.values()){deviceOperations.sort((a,b)=>a.seq-b.seq);for(let index=0;index<deviceOperations.length;index+=250){const batch=createBatch(deviceOperations.slice(index,index+250));await transport.putBatch(batch);uploaded+=batch.ops.length}}await store.putMeta(BOOTSTRAP_META,{...pending,pending:false,uploaded_at:new Date().toISOString()});return uploaded}
async function syncNow(){if(syncPromise)return syncPromise;syncPromise=(async()=>{const hasCredential=Boolean(await store.getMeta(TOKEN_META));if(navigator.onLine===false){setStatus(`Offline · ${hasCredential?'Dropbox ansluten · ':''}resultaten finns lokalt`,'warning');return null}const token=await currentAccessToken();if(!token){setStatus('Lokal master · Dropbox ej ansluten','warning');connectButton.textContent='Anslut Dropbox';return null}connectButton.textContent='Synka Dropbox';setStatus('Synkar resultaten och läser Matrikel…');const transport=new DropboxTransport({accessToken:token,id:'dropbox-korpholmenrunt',opsRoot:'/korpholmenrunt/ops'});const bootstrap=await uploadBootstrapOps(transport);const result=await new SyncEngine({repository,transport}).syncOnce();await matrikelMaster.sync(new DropboxTransport({accessToken:token,id:'dropbox-matrikel-read',opsRoot:'/matrikel/ops',readOnly:true}));render();setStatus(`Synkad · ${results().length} resultat · ${bootstrap+result.uploadedOps} upp, ${result.downloadedOps} ned · namn från Matrikel`,'ok');return result})().catch(error=>{console.error(error);if(isOfflineError(error)){setStatus('Offline · lokal master tillgänglig','warning');return null}setStatus(`Åtgärd krävs · ${error.message}`,'error');throw error}).finally(()=>{syncPromise=null});return syncPromise}
async function connectDropbox(){sessionStorage.setItem('korpholmen:oauth-return',new URL('korpholmenrunt/',redirectUri()).pathname);const attempt=await beginDropboxOAuth({clientId:DROPBOX_CLIENT_ID,redirectUri:redirectUri(),scopes:DROPBOX_SCOPES});location.assign(attempt.url)}
async function bootstrapLocal(){if(!isSourceTree)throw new Error('Startkopian kan bara aktiveras från källappen');if((await store.getAllOps()).length)throw new Error('Startkopian kan bara aktiveras i en tom lokal databas. Befintlig data har inte ändrats.');const response=await fetch(LOCAL_BOOTSTRAP_URL,{cache:'no-store'});if(!response.ok)throw new Error(`Startkopian kunde inte läsas (${response.status})`);const data=await response.json();if(data.operations_version!==1||!Array.isArray(data.operations))throw new Error('Startkopian har fel format');const deviceIds=new Set(data.device_ids||[data.device_id]);if(!data.device_id||!deviceIds.has(data.device_id)||data.operations.some(operation=>!deviceIds.has(operation.device_id)))throw new Error('Startkopians device-id:n är inkonsekventa');data.operations.forEach(validateOperation);await repository.applyRemoteOps(data.operations);await store.putMeta(BOOTSTRAP_META,{pending:true,device_id:data.device_id,device_ids:[...deviceIds],migration_id:data.migration_id,operations:data.operations.length});render();setStatus('Aktuell källmaster inläst lokalt · anslut Dropbox för uppladdning','ok')}

document.addEventListener('click',event=>{
  const view=event.target.closest('[data-view]')?.dataset.view;if(view){ui.view=view;ui.profile=null;render();app.focus()}
  const year=event.target.closest('[data-year]')?.dataset.year;if(year){ui.year=year;$('#year-filter').value=year;ui.view='resultat';render()}
  const actionNode=event.target.closest('[data-action]');const action=actionNode?.dataset.action;
  const resultId=event.target.closest('[data-result-id]')?.dataset.resultId;if(resultId&&!actionNode)openResultDialog(resultId);
  const profile=event.target.closest('[data-profile]')?.dataset.profile;if(profile){ui.profile=profile;render()}
  if(action==='back-profiles'){ui.profile=null;render()}if(action==='sort-results'){const key=actionNode.dataset.sortKey;if(ui.sortKey===key)ui.sortDirection=ui.sortDirection==='asc'?'desc':'asc';else{ui.sortKey=key;ui.sortDirection='asc'}render()}if(action==='toggle-split-review'){ui.splitReview=!ui.splitReview;ui.view='resultat';render()}if(action==='open-result')openResultDialog(resultId);if(action==='approve-result')approveResult(resultId).catch(error=>setStatus(error.message,'error'));if(action==='confirm-person')confirmPerson(event.target.closest('[data-link-id]').dataset.linkId).catch(error=>setStatus(error.message,'error'));if(action==='confirm-boat')confirmBoat(resultId).catch(error=>setStatus(error.message,'error'));if(action==='keep-person-unlinked')keepPersonUnlinked(actionNode.dataset.linkId).catch(error=>setStatus(error.message,'error'));if(action==='keep-boat-unlinked')keepBoatUnlinked(resultId).catch(error=>setStatus(error.message,'error'));if(action==='quick-confirm-person')confirmPersonCandidate(actionNode.dataset.linkId,actionNode.dataset.personId).catch(error=>setStatus(error.message,'error'));if(action==='quick-confirm-boat')confirmBoatCandidate(resultId,actionNode.dataset.boatId).catch(error=>setStatus(error.message,'error'));if(action==='split-participant'){let parts=[];try{parts=JSON.parse(actionNode.dataset.splitParts||'[]')}catch{}splitParticipantLink(actionNode.dataset.linkId,parts).catch(error=>setStatus(error.message,'error'))}
});
const renderSearch=debounce(render,120);
$('#global-search').addEventListener('input',event=>{ui.search=event.target.value;if(ui.view==='oversikt')ui.view='resultat';renderSearch()});
$('#clear-search').addEventListener('click',()=>{renderSearch.cancel();ui.search='';$('#global-search').value='';render()});
$('#year-filter').addEventListener('change',event=>{ui.year=event.target.value;ui.view='resultat';render()});
$('#class-filter').addEventListener('change',event=>{ui.className=event.target.value;ui.view='resultat';render()});
$('#course-filter').addEventListener('change',event=>{ui.course=event.target.value;ui.view='resultat';render()});
$('#new-result').addEventListener('click',()=>openResultDialog());
$('#save-result').addEventListener('click',()=>saveResult().catch(error=>setStatus(error.message,'error')));
$('#export-csv').addEventListener('click',exportCsv);
standardizeClassesButton.addEventListener('click',()=>applyClassStandard().catch(error=>setStatus(error.message,'error')));
connectButton.addEventListener('click',()=>currentAccessToken().then(token=>token?syncNow():connectDropbox()).catch(error=>setStatus(error.message,'error')));
bootstrapButton.addEventListener('click',()=>bootstrapLocal().catch(error=>setStatus(error.message,'error')));
app.addEventListener('input',event=>runInlineUpdate(event.target));
app.addEventListener('change',event=>{if(event.target.id==='duel-a'){ui.duelA=event.target.value;render()}if(event.target.id==='duel-b'){ui.duelB=event.target.value;render()}runInlineUpdate(event.target,true)});
window.addEventListener('online',()=>syncNow().catch(()=>{}));window.addEventListener('offline',()=>syncNow().catch(()=>{}));

async function init(){const serviceWorkerPromise=registerServiceWorker();const db=await openSlaktlandskapDB({name:'korpholmen-runt'});store=new IndexedDBStore(db);repository=await new Repository({store,deviceId:await deviceId()}).init();matrikelMaster=await new ReadOnlyMaster({store,cacheKey:'matrikel'}).init();bootstrapButton.hidden=!isSourceTree;const params=new URLSearchParams(location.search);if(params.has('person')){ui.view='profiler';ui.profile=`person:${params.get('person')}`}if(params.has('boat')){ui.view='profiler';ui.profile=`boat:${params.get('boat')}`}render();await completeOAuthCallbackIfNeeded();await syncNow();await serviceWorkerPromise}
init().catch(error=>{console.error(error);setStatus(`Kunde inte starta · ${error.message}`,'error')});
