import {
  DropboxTransport,
  IndexedDBStore,
  Repository,
  SyncEngine,
  beginDropboxOAuth,
  completeDropboxOAuth,
  createBatch,
  exchangeDropboxRefreshToken,
  openSlaktlandskapDB,
  validateOperation,
} from '../../../packages/core/data-layer.js';
import { DROPBOX_CLIENT_ID, DROPBOX_SCOPES, LOCAL_BOOTSTRAP_URLS } from './config.js';
import { boatOptionLabel, boatReferenceLines } from './boat-reference.js';

const $=selector=>document.querySelector(selector);
const app=$('#app');const statusNode=$('#sync-status');const connectButton=$('#connect-dropbox');const bootstrapButton=$('#bootstrap-local');
const isSourceTree=location.pathname.includes('/apps/klubbhistorik/');
const TOKEN_META='dropbox:refresh-token';const BOOTSTRAP_META='bootstrap:klubbhistorik-pilot-2026-08-02';
const ui={view:'oversikt',search:'',releaseId:'matrikel-1980',layer:'normalized',kind:'person',from:'matrikel-1980',to:'matrikel-1986',personId:null};
let store;let repository;let accessToken=null;let accessTokenExpiresAt=0;let syncPromise=null;

const escapeHtml=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const escapeAttribute=escapeHtml;
const normalize=value=>String(value||'').normalize('NFD').replace(/\p{Diacritic}/gu,'').toLocaleLowerCase('sv').replace(/[^a-z0-9]+/g,' ').trim();
const confirmed=item=>Boolean(item?.confirmed&&item?.person_id||item?.confirmed&&item?.boat_id);
const recordList=type=>repository?repository.listEntities(type).map(entity=>({id:entity.entity_id,...entity.fields})):[];
const releaseMoment=release=>String(release?.as_of||release?.year||'');
const releaseCompare=(a,b)=>releaseMoment(a).localeCompare(releaseMoment(b),'sv')||String(a.title||'').localeCompare(String(b.title||''),'sv')||a.id.localeCompare(b.id,'sv');
const releases=()=>recordList('matrikel-release').sort(releaseCompare);
const personOccurrences=()=>recordList('person-occurrence').sort((a,b)=>a.release_id.localeCompare(b.release_id)||a.order-b.order);
const boatOccurrences=()=>recordList('boat-occurrence').sort((a,b)=>a.release_id.localeCompare(b.release_id)||a.order-b.order);
const sourceRows=()=>recordList('source-row').sort((a,b)=>a.release_id.localeCompare(b.release_id)||a.kind.localeCompare(b.kind)||a.order-b.order);
const personRefs=()=>recordList('person-ref').sort((a,b)=>a.display_name.localeCompare(b.display_name,'sv'));
const boatRefs=()=>recordList('boat-ref').sort((a,b)=>boatOptionLabel(a).localeCompare(boatOptionLabel(b),'sv'));
const personMap=()=>new Map(personRefs().map(item=>[item.external_id,item]));
const boatMap=()=>new Map(boatRefs().map(item=>[item.external_id,item]));
const releaseMap=()=>new Map(releases().map(item=>[item.id,item]));
const statusLabel=status=>({active:'Aktiv',passive:'Passiv',junior:'Junior',corresponding:'Korresponderande',listed:'Listad'}[status]||status||'Okänd');
const boatCategoryLabel=category=>({registered:'Inregistrerat fartyg','registered-passive':'Fartyg vid passivavsnitt','registered-junior':'Fartyg vid junioravsnitt','registered-corresponding':'Fartyg vid korresponderande','deregistered-or-renamed':'Avregistrerat eller namnändrat'}[category]||category||'Fartyg');
const matchLabel=status=>({kopplad:'Kopplad',godkand:'Godkänd',foreslagen:'Föreslagen',saknas:'Saknas',manuell:'Manuell'}[status]||status||'Okänd');
const isOfflineError=error=>navigator.onLine===false||error instanceof TypeError||/failed to fetch|load failed|networkerror|internetanslutning|network connection/i.test(String(error?.message||error));
function setStatus(text,tone=''){statusNode.textContent=text;statusNode.className=tone?`status-${tone}`:''}
function deviceId(){const key='korpholmen:klubbhistorik-device-id';let id=localStorage.getItem(key);if(!id){id=`klubbhistorik-web-${crypto.randomUUID()}`;localStorage.setItem(key,id)}return id}
function redirectUri(){return new URL(isSourceTree?'../../':'../',location.href).href}

function duplicateGroups(){
  const groups=[];
  for(const release of releases()){
    const byPerson=new Map();
    for(const item of personOccurrences().filter(entry=>entry.release_id===release.id&&entry.person_id&&entry.confirmed)){
      if(!byPerson.has(item.person_id))byPerson.set(item.person_id,[]);byPerson.get(item.person_id).push(item);
    }
    for(const [personId,items] of byPerson)if(items.length>1)groups.push({release_id:release.id,person_id:personId,items});
  }
  return groups;
}
function invalidDates(){return personOccurrences().filter(item=>item.birth_date_raw&&!item.birth_date)}
function unresolvedPeople(){return personOccurrences().filter(item=>!item.person_id||!item.confirmed)}
function unresolvedBoats(){return boatOccurrences().filter(item=>!item.boat_id||!item.confirmed)}
function reviewCount(){return unresolvedPeople().length+unresolvedBoats().length+duplicateGroups().length+invalidDates().length}
function updateControls(){
  const all=releases();const select=$('#release-filter');const current=select.value||ui.releaseId;
  select.innerHTML=all.map(item=>`<option value="${escapeAttribute(item.id)}">${escapeHtml(releaseMoment(item))} · ${escapeHtml(item.title)}</option>`).join('');
  ui.releaseId=all.some(item=>item.id===current)?current:all[0]?.id||'';select.value=ui.releaseId;
  $('#review-count').textContent=String(reviewCount());
  document.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('aktiv',button.dataset.view===ui.view));
}
function emptyState(){return `<section class="tomt"><span>◎</span><h2>Pilotmastern väntar</h2><p>Anslut Dropbox för den levande Klubbhistoriken.${isSourceTree?' På localhost kan du också aktivera den reproducerbara startmastern.':''}</p></section>`}
function coverage(release){const items=personOccurrences().filter(item=>item.release_id===release.id);return {total:items.length,connected:items.filter(item=>item.person_id&&item.confirmed).length}}
function releaseCard(release){const c=coverage(release);const percent=c.total?c.connected/c.total*100:0;return `<button class="releasekort" data-open-release="${escapeAttribute(release.id)}"><p class="overrad">${escapeHtml(release.release_type)}</p><h3>${escapeHtml(releaseMoment(release))}</h3><p>${escapeHtml(release.title)}</p><div class="tackning" title="${c.connected} av ${c.total} personrader kopplade"><i style="width:${percent}%"></i></div><div class="chips"><span class="chip">${c.total} personrader</span>${release.boat_occurrence_count?`<span class="chip">${release.boat_occurrence_count} båtar</span>`:''}<span class="chip">${c.total-c.connected} olösta</span></div></button>`}
function renderOverview(){
  if(!releases().length)return emptyState();
  const people=personOccurrences();const boats=boatOccurrences();const connected=people.filter(item=>item.person_id&&item.confirmed).length;const root=recordList('club-history-root')[0];
  const issues=reviewCount();const names=recordList('name-change-candidate');const duplicates=duplicateGroups();
  return `<section class="hero"><article class="herokort"><p class="overrad">${releases().length} källbundna ögonblick</p><h2>Klubben förändras. Källan ligger kvar.</h2><p>Varje rad visas både som den skrevs och som en försiktigt normaliserad koppling till stabila personer och båtar. Frånvaro ur en matrikel tolkas aldrig automatiskt som utträde.</p><div class="herosiffror"><div><strong>${people.length}</strong><span>bevarade medlemsrader</span></div><div><strong>${boats.length}</strong><span>båtförekomster</span></div><div><strong>${connected}</strong><span>godkända personkopplingar</span></div></div></article><aside class="auditkort"><div><p class="overrad">Förlustkontroll</p><h2>${issues} öppna kontrollpunkter</h2><div class="auditlista"><div class="auditrad"><span>Personrader</span><b>${people.length}/${people.length}</b></div><div class="auditrad"><span>Källrader totalt</span><b>${sourceRows().length}</b></div><div class="auditrad"><span>Personer till granskning</span><b>${unresolvedPeople().length}</b></div><div class="auditrad"><span>Båtar till granskning</span><b>${unresolvedBoats().length}</b></div></div></div><span class="auditstatus">Alla källrader redovisade</span></aside></section><section class="panelgrid"><article class="panel span8"><p class="overrad">Tidsrälsen</p><h2>Matrikelutgåvor</h2><div class="releasegrid">${releases().map(releaseCard).join('')}</div></article><article class="panel span4"><p class="overrad">Det som inte får döljas</p><h2>Kontrollfynd</h2><div class="auditlista"><div class="auditrad"><span>Dubblettgrupper</span><b>${duplicates.length}</b></div><div class="auditrad"><span>Ogiltiga rådatum</span><b>${invalidDates().length}</b></div><div class="auditrad"><span>Belagda namnskiften</span><b>${names.length}</b></div><div class="auditrad"><span>Personreferenser</span><b>${personRefs().length}</b></div></div><p class="hash">${escapeHtml(root?.source_hashes?.historic||'')}</p></article><article class="panel span12"><p class="overrad">Verkliga namnförändringar</p><h2>Inte rena stavfel</h2><div class="releasegrid">${names.map(item=>`<article class="namnbyte"><span>${escapeHtml(releaseMoment(releaseMap().get(item.from_release_id)))} → ${escapeHtml(releaseMoment(releaseMap().get(item.to_release_id)))}</span><strong>${escapeHtml(item.from_name)} → ${escapeHtml(item.to_name)}</strong><span>${escapeHtml(item.basis)}</span></article>`).join('')}</div></article></section>`;
}

function filtered(values,fields){const query=normalize(ui.search);return !query?values:values.filter(item=>normalize(fields.map(field=>item[field]).join(' ')).includes(query))}
function boatReferenceHtml(reference){
  if(!reference)return '<p class="batreferens-tom">Ingen båt vald.</p>';
  const lines=boatReferenceLines(reference);
  return `<article class="batreferens"><h4>${escapeHtml(lines.title)}</h4>${lines.technical?`<p><b>Typ, modell och tid</b><span>${escapeHtml(lines.technical)}</span></p>`:''}${lines.owner?`<p><b>Ägare/anknytning</b><span>${escapeHtml(lines.owner)}</span></p>`:''}${lines.names?`<p><b>Namnhistorik</b><span>${escapeHtml(lines.names)}</span></p>`:''}${lines.sources?`<p><b>Källor</b><span>${escapeHtml(lines.sources)}</span></p>`:''}<a href="${escapeAttribute(reference.url)}">Öppna i Båtregister ↗</a></article>`;
}
function layerSwitch(){return `<div class="lagervaxel"><button class="${ui.layer==='source'?'aktiv':''}" data-layer="source">Som källan skrevs</button><button class="${ui.layer==='normalized'?'aktiv':''}" data-layer="normalized">Normaliserad värld</button></div>`}
function kindSwitch(release){return `<div class="typvaxel"><button class="${ui.kind==='person'?'aktiv':''}" data-kind="person">Personer</button><button class="${ui.kind==='boat'?'aktiv':''}" data-kind="boat" ${release.boat_occurrence_count?'':'disabled'}>Båtar</button></div>`}
function canonicalSourceRows(releaseId,kind){const all=sourceRows().filter(item=>item.release_id===releaseId&&item.kind===kind);const canonical=all.filter(item=>item.source_document_id&&item.id.startsWith('source-row:canonical:'));return canonical.length?canonical:all}
function renderSourceEdition(release){
  const kind=ui.kind==='boat'?'boat':'person';const rows=filtered(canonicalSourceRows(release.id,kind),['raw_text']);
  if(!rows.length)return `<section class="tomt"><h2>Inga ${kind==='boat'?'båtrader':'personrader'} i denna utgåva</h2></section>`;
  return `<section class="originalblock"><article class="originalsektion"><h3>${kind==='boat'?'Fartygskolumnen':'Medlemskolumnen'} · ordagrann</h3>${rows.map(item=>`<div class="originalrad"><span>${String(item.order).padStart(2,'0')}${item.source_page?` · s. ${item.source_page}`:''}${item.category?` · ${escapeHtml(kind==='boat'?boatCategoryLabel(item.category):statusLabel(item.category))}`:''}</span><code class="rarad">${escapeHtml(item.raw_text)}</code>${item.source_annotation?`<small>${escapeHtml(item.source_annotation)}</small>`:''}${item.normalization_note?`<small class="normaliseringsnot">Normalisering: ${escapeHtml(item.normalization_note)}</small>`:''}</div>`).join('')}</article></section>`;
}
function renderNormalizedEdition(release){
  if(ui.kind==='boat'){
    const map=boatMap();const rows=filtered(boatOccurrences().filter(item=>item.release_id===release.id),['boat_name_raw','source_line_raw']);
    if(!rows.length)return `<section class="tomt"><h2>Utgåvan innehåller ingen fartygskolumn</h2><p>Det är en egenskap hos källan, inte ett påstående om att klubben saknade båtar.</p></section>`;
    return `<div class="tabellskal"><table><thead><tr><th>#</th><th>Som skrivet</th><th>Normaliserad båt</th><th>Prefix/år</th><th>Matchning</th></tr></thead><tbody>${rows.map(item=>{const boat=map.get(item.boat_id);const lines=boat?boatReferenceLines(boat):null;return `<tr><td>${item.order}</td><td><strong>${escapeHtml(item.boat_name_raw)}</strong><small>${escapeHtml(item.source_line_raw)}</small><small>${escapeHtml([item.source_page?`sida ${item.source_page}`:'',boatCategoryLabel(item.source_category),item.source_annotation].filter(Boolean).join(' · '))}</small></td><td>${boat?`<a href="${escapeAttribute(boat.url)}">${escapeHtml(lines.title)}</a><small>${escapeHtml([lines.technical,lines.owner].filter(Boolean).join(' · '))}</small>`:'—'}</td><td>${escapeHtml([item.prefix,item.registry_year_raw].filter(Boolean).join(' · ')||'—')}</td><td><span class="statuschip ${escapeAttribute(item.match_status)}">${escapeHtml(matchLabel(item.match_status))}</span><small>${escapeHtml(item.match_method)}</small></td></tr>`}).join('')}</tbody></table></div>`;
  }
  const map=personMap();const rows=filtered(personOccurrences().filter(item=>item.release_id===release.id),['person_name_raw','club_name_core_raw','club_name_raw','island_raw']);
  return `<div class="tabellskal"><table><thead><tr><th>#</th><th>Källans personnamn</th><th>Stabil person</th><th>Status</th><th>År/ö</th><th>Matchning</th></tr></thead><tbody>${rows.map(item=>{const person=map.get(item.person_id);return `<tr><td>${item.order}</td><td><strong>${escapeHtml(item.person_name_raw)}</strong>${item.club_name_core_raw||item.club_name_raw?`<small>${escapeHtml(item.club_name_core_raw||item.club_name_raw)}</small>`:''}${item.source_page||item.source_annotation?`<small>${escapeHtml([item.source_page?`sida ${item.source_page}`:'',item.source_annotation].filter(Boolean).join(' · '))}</small>`:''}</td><td>${person?`<a href="${escapeAttribute(person.url)}">${escapeHtml(person.display_name)}</a>`:'—'}</td><td>${escapeHtml(statusLabel(item.membership_status))}</td><td>${escapeHtml([item.induction_year_raw||item.birth_year,item.island_raw].filter(Boolean).join(' · ')||'—')}</td><td><span class="statuschip ${escapeAttribute(item.match_status)}">${escapeHtml(matchLabel(item.match_status))}</span><small>${escapeHtml(item.match_method)}</small></td></tr>`}).join('')}</tbody></table></div>`;
}
function renderEdition(){const release=releaseMap().get(ui.releaseId)||releases()[0];if(!release)return emptyState();if(!release.boat_occurrence_count&&ui.kind==='boat')ui.kind='person';return `<header class="sidtitel"><div><p class="overrad">${escapeHtml(release.release_type)}</p><h2>${escapeHtml(releaseMoment(release))} · ${escapeHtml(release.title)}</h2><p>${release.person_row_count} personrader${release.boat_occurrence_count?` · ${release.boat_occurrence_count} båtförekomster`:''}. Ingen kolumnparning görs utan källstöd.</p></div><div>${layerSwitch()}${kindSwitch(release)}</div></header>${ui.layer==='source'?renderSourceEdition(release):renderNormalizedEdition(release)}`}

function occurrenceMap(releaseId){const map=new Map();for(const item of personOccurrences().filter(entry=>entry.release_id===releaseId&&entry.person_id&&entry.confirmed)){if(!map.has(item.person_id))map.set(item.person_id,[]);map.get(item.person_id).push(item)}return map}
function changeList(title,items,empty='Inga'){const pMap=personMap();return `<article class="forandringskolumn"><p class="overrad">${items.length} personer</p><h3>${escapeHtml(title)}</h3>${items.length?items.map(id=>`<button class="changeitem" data-person-id="${escapeAttribute(id)}"><b>${escapeHtml(pMap.get(id)?.display_name||id)}</b><span>Visa tidslinje →</span></button>`).join(''):`<p>${escapeHtml(empty)}</p>`}</article>`}
function renderChanges(){
  const all=releases();if(!all.length)return emptyState();if(!all.some(item=>item.id===ui.from))ui.from=all[0].id;if(!all.some(item=>item.id===ui.to))ui.to=all[1]?.id||all[0].id;
  const from=releaseMap().get(ui.from),to=releaseMap().get(ui.to);const before=occurrenceMap(ui.from),after=occurrenceMap(ui.to);const newIds=[...after.keys()].filter(id=>!before.has(id));const missingIds=[...before.keys()].filter(id=>!after.has(id));
  const statusChanges=[...before.keys()].filter(id=>after.has(id)&&before.get(id)[0].membership_status!==after.get(id)[0].membership_status).map(id=>({id,from:before.get(id)[0].membership_status,to:after.get(id)[0].membership_status}));
  const nameChanges=recordList('name-change-candidate').filter(item=>item.from_release_id===ui.from&&item.to_release_id===ui.to);
  const options=all.map(item=>`<option value="${escapeAttribute(item.id)}">${escapeHtml(releaseMoment(item))}</option>`).join('');const fromLabel=releaseMoment(from),toLabel=releaseMoment(to);
  return `<header class="sidtitel"><div><p class="overrad">Tidsjämförelse</p><h2>${escapeHtml(fromLabel)} → ${escapeHtml(toLabel)}</h2><p>Förändringar räknas endast över godkända stabila person-ID:n.</p></div><div class="forandringsval"><select id="change-from">${options}</select><span>→</span><select id="change-to">${options}</select></div></header><p class="varning"><strong>Frånvaro är inte ett utträde.</strong> ”Inte observerad ${escapeHtml(toLabel)}” betyder bara att personen inte finns i den utgåva som bevarats.</p>${nameChanges.length?`<section class="panel span12"><p class="overrad">Belagda namnförändringar</p><div class="releasegrid">${nameChanges.map(item=>`<article class="namnbyte"><span>${escapeHtml(fromLabel)} → ${escapeHtml(toLabel)}</span><strong>${escapeHtml(item.from_name)} → ${escapeHtml(item.to_name)}</strong><span>${escapeHtml(item.basis)}</span></article>`).join('')}</div></section>`:''}<section class="forandringsgrid" style="margin-top:1rem">${changeList(`Nya i ${toLabel}`,newIds)}${changeList(`Inte observerade ${toLabel}`,missingIds)}</section><section class="panel span12" style="margin-top:1rem"><p class="overrad">Medlemskategori</p><h2>Ändrad status</h2>${statusChanges.length?statusChanges.map(item=>`<div class="changeitem"><b>${escapeHtml(personMap().get(item.id)?.display_name||item.id)}</b><span>${escapeHtml(statusLabel(item.from))} → ${escapeHtml(statusLabel(item.to))}</span></div>`).join(''):'<p>Ingen statusförändring mellan de kopplade raderna.</p>'}</section>`;
}

function profileCatalog(){const pMap=personMap();const grouped=new Map();for(const item of personOccurrences().filter(entry=>entry.person_id&&entry.confirmed)){if(!grouped.has(item.person_id))grouped.set(item.person_id,[]);grouped.get(item.person_id).push(item)}return [...grouped].map(([id,items])=>({id,person:pMap.get(id),items:items.sort((a,b)=>releaseCompare(releaseMap().get(a.release_id),releaseMap().get(b.release_id)))})).filter(entry=>entry.person).sort((a,b)=>a.person.display_name.localeCompare(b.person.display_name,'sv'))}
function renderPersonDetail(profile){const changes=recordList('name-change-candidate').filter(item=>item.person_id===profile.id);return `<header class="personhuvud"><div><p class="overrad">Stabil personidentitet</p><h2>${escapeHtml(profile.person.display_name)}</h2><p>${escapeHtml([profile.person.birth?`född ${profile.person.birth}`:'',profile.person.club_name].filter(Boolean).join(' · '))}</p></div><a href="${escapeAttribute(profile.person.url)}">Öppna i Matrikel ↗</a></header>${changes.length?`<div class="varning">${changes.map(item=>`<strong>${escapeHtml(item.from_name)} → ${escapeHtml(item.to_name)}</strong> · ${escapeHtml(item.basis)}`).join('<br>')}</div>`:''}<section class="tidslinje">${profile.items.map(item=>{const release=releaseMap().get(item.release_id);return `<article class="tidspost"><p class="overrad">${escapeHtml(releaseMoment(release))} · ${escapeHtml(statusLabel(item.membership_status))}</p><h3>${escapeHtml(item.person_name_raw)}</h3><p>${escapeHtml([item.club_name_core_raw||item.club_name_raw,item.island_raw,item.induction_year_raw?`inval ${item.induction_year_raw}`:''].filter(Boolean).join(' · ')||'Inga ytterligare fält i utgåvan')}</p><span class="statuschip ${escapeAttribute(item.match_status)}">${escapeHtml(matchLabel(item.match_status))}</span></article>`}).join('')}</section>`}
function renderPeople(){const catalog=profileCatalog();if(ui.personId){const profile=catalog.find(item=>item.id===ui.personId);if(profile)return `<header class="sidtitel"><button class="sekundar" data-action="back-people">← Alla personer</button></header>${renderPersonDetail(profile)}`;ui.personId=null}const query=normalize(ui.search);const visible=catalog.filter(item=>!query||normalize([item.person.display_name,item.person.club_name,...item.items.map(row=>row.person_name_raw)].join(' ')).includes(query));return `<header class="sidtitel"><div><p class="overrad">Samma person genom flera namn</p><h2>Personhistorik</h2><p>${visible.length} personer med minst en godkänd matrikelkoppling.</p></div></header><div class="profilgrid">${visible.map(profile=>`<button class="profilkort" data-person-id="${escapeAttribute(profile.id)}"><h3>${escapeHtml(profile.person.display_name)}</h3><p>${escapeHtml(profile.person.club_name||'Inget nuvarande klubbnamn')}</p><div class="profilmeta"><span>${profile.items.map(item=>releaseMoment(releaseMap().get(item.release_id))).join(' · ')}</span><b>${profile.items.length} belägg</b></div></button>`).join('')}</div>`}

function latestValue(items,reader){for(const item of [...items].reverse()){const value=reader(item);if(value!==''&&value!==null&&value!==undefined)return value}return null}
function matrixCatalog(){return profileCatalog().map(profile=>{const byRelease=new Map();for(const item of profile.items){if(!byRelease.has(item.release_id))byRelease.set(item.release_id,[]);byRelease.get(item.release_id).push(item)}const inductionYears=profile.items.map(item=>item.induction_year).filter(value=>value!==null&&value!==undefined&&value!=='').map(Number).filter(Number.isFinite);const inductionYear=inductionYears.length?Math.min(...inductionYears):null;const clubName=profile.person.club_name||latestValue(profile.items,item=>item.club_name_core_raw||item.club_name_raw)||'';const birthYear=profile.person.birth||latestValue(profile.items,item=>item.birth_year)||null;return {...profile,byRelease,inductionYear,clubName,birthYear}}).sort((a,b)=>(a.inductionYear??9999)-(b.inductionYear??9999)||a.person.display_name.localeCompare(b.person.display_name,'sv'))}
function matrixReleaseHeading(release){const moment=releaseMoment(release);const [year,...rest]=moment.split('-');let detail=rest.join('-');if(!detail&&release.id==='matrikel-2025')detail='Numbers';if(!detail&&release.id==='matrikel-2025-standard')detail='standard';return `<span>${escapeHtml(year)}</span>${detail?`<small>${escapeHtml(detail)}</small>`:''}`}
function matrixCell(profile,release){const items=profile.byRelease.get(release.id)||[];if(!items.length)return '<td class="matriscell matris-franvaro" aria-label="Inte observerad"></td>';const statuses=[...new Set(items.map(item=>item.membership_status||'listed'))];const statusClass=statuses.length===1?`status-${statuses[0]}`:'status-multiple';const detail=[releaseMoment(release),...statuses.map(statusLabel),...new Set(items.map(item=>item.person_name_raw))].join(' · ');return `<td class="matriscell ${escapeAttribute(statusClass)}"><span title="${escapeAttribute(detail)}" aria-label="${escapeAttribute(detail)}">×</span></td>`}
function renderMatrix(){const all=matrixCatalog();const query=normalize(ui.search);const visible=all.filter(profile=>!query||normalize([profile.person.display_name,profile.clubName,profile.birthYear,profile.inductionYear,...profile.items.map(item=>item.person_name_raw)].join(' ')).includes(query));const editions=releases();return `<header class="sidtitel matrissidtitel"><div><p class="overrad">Personer genom alla källögonblick</p><h2>Medlemsmatris</h2><p>${visible.length} säkert identifierade personer · ${editions.length} matrikelutgåvor. Tom ruta betyder endast ”inte observerad”.</p></div></header><div class="matrisinfo"><p><strong>Invalsår visas bara när det uttryckligen står i en källa.</strong> ${unresolvedPeople().length} ännu omatchade personrader placeras inte i matrisen förrän identiteten är godkänd.</p><div class="matrislegend" aria-label="Förklaring"><span class="status-active">× Aktiv</span><span class="status-junior">× Junior</span><span class="status-passive">× Passiv</span><span class="status-corresponding">× Korresponderande</span><span class="status-listed">× Listad, status saknas</span><span class="status-multiple">× Flera källrader/statusar</span></div></div><div class="matrisskal" tabindex="0" aria-label="Horisontellt rullbar medlemsmatris"><table class="medlemsmatris"><caption class="sr-only">Invalsår, person, klubbnamn, födelseår och förekomst i varje matrikel</caption><thead><tr><th class="matrismeta matris-inval">Inval</th><th class="matrismeta matris-person">Person</th><th class="matrismeta matris-klubbnamn">Klubbnamn</th><th class="matrismeta matris-fodd">Född</th>${editions.map(release=>`<th class="matrisutgava" title="${escapeAttribute(release.title)}">${matrixReleaseHeading(release)}</th>`).join('')}</tr></thead><tbody>${visible.map(profile=>`<tr><td class="matrismeta matris-inval">${profile.inductionYear??'—'}</td><th scope="row" class="matrismeta matris-person"><button data-person-id="${escapeAttribute(profile.id)}">${escapeHtml(profile.person.display_name)}</button></th><td class="matrismeta matris-klubbnamn">${escapeHtml(profile.clubName||'—')}</td><td class="matrismeta matris-fodd">${escapeHtml(profile.birthYear||'—')}</td>${editions.map(release=>matrixCell(profile,release)).join('')}</tr>`).join('')}</tbody></table></div>`}

function selectOptions(refs,candidates,labeler,selectedId=''){
  const candidateSet=new Set(candidates||[]);const preferred=refs.filter(item=>candidateSet.has(item.external_id));const rest=refs.filter(item=>!candidateSet.has(item.external_id));
  const options=items=>items.map(item=>`<option value="${escapeAttribute(item.external_id)}" ${item.external_id===selectedId?'selected':''}>${escapeHtml(labeler(item))}</option>`).join('');
  return '<option value="">Välj identitet…</option>'+(preferred.length?`<optgroup label="Föreslagna">${options(preferred)}</optgroup>`:'')+`<optgroup label="Alla identiteter">${options(rest)}</optgroup>`;
}
function boatReviewCard(item,reviewed=false){
  const bMap=boatMap();const rMap=releaseMap();const candidates=(item.candidate_ids||[]).map(id=>bMap.get(id)).filter(Boolean);const selected=reviewed?bMap.get(item.boat_id):null;
  return `<article class="reviewkort"><div class="reviewrubrik"><div><p class="overrad">${escapeHtml(releaseMoment(rMap.get(item.release_id)))} · båtrad ${item.source_line_order}${item.source_page?` · sida ${item.source_page}`:''}</p><h3>${escapeHtml(item.boat_name_raw)}</h3></div><b>${escapeHtml(matchLabel(item.match_status))}</b></div><p>${escapeHtml(item.source_line_raw)}</p>${item.source_category?`<p class="beslutsnot">${escapeHtml(boatCategoryLabel(item.source_category))}${item.source_annotation?` · ${escapeHtml(item.source_annotation)}`:''}</p>`:''}${item.decision_note?`<p class="beslutsnot">${escapeHtml(item.decision_note)}</p>`:''}${!reviewed&&candidates.length?`<div class="batkandidatlista">${candidates.map(boatReferenceHtml).join('')}</div>`:''}<div class="reviewaction"><select data-boat-select="${escapeAttribute(item.id)}">${selectOptions(boatRefs(),item.candidate_ids,boatOptionLabel,item.boat_id||'')}</select><button class="primar" data-action="confirm-boat" data-occurrence-id="${escapeAttribute(item.id)}">${reviewed?'Spara ändring':'Godkänn koppling'}</button></div><div class="batval-preview" data-boat-preview="${escapeAttribute(item.id)}">${selected?boatReferenceHtml(selected):''}</div></article>`;
}
function renderReview(){
  const pRefs=personRefs(),rMap=releaseMap(),pMap=personMap();const people=filtered(unresolvedPeople(),['person_name_raw','club_name_raw','release_id']);const boats=filtered(unresolvedBoats(),['boat_name_raw','source_line_raw','release_id']);const duplicates=duplicateGroups();const dates=invalidDates();
  const reviewed=boatOccurrences().filter(item=>item.boat_id&&item.confirmed&&['manuell','godkand'].includes(item.match_status));
  return `<header class="sidtitel"><div><p class="overrad">Inget tyst avgörande</p><h2>Granskningskö</h2><p>Beslut här påverkar endast Klubbhistorik. Matrikel och Båtregister skrivs inte om.</p></div></header><section class="panel span12"><div class="reviewrubrik"><div><p class="overrad">Personidentiteter</p><h2>${people.length} öppna rader</h2></div></div><div class="reviewgrid">${people.map(item=>`<article class="reviewkort"><div class="reviewrubrik"><div><p class="overrad">${escapeHtml(releaseMoment(rMap.get(item.release_id)))} · rad ${item.order}</p><h3>${escapeHtml(item.person_name_raw)}</h3></div><b>${escapeHtml(matchLabel(item.match_status))}</b></div><p>${escapeHtml(item.decision_note||item.match_method)}${item.club_name_core_raw||item.club_name_raw?` · ${escapeHtml(item.club_name_core_raw||item.club_name_raw)}`:''}</p><div class="reviewaction"><select data-person-select="${escapeAttribute(item.id)}">${selectOptions(pRefs,item.candidate_ids,item=>item.display_name)}</select><button class="primar" data-action="confirm-person" data-occurrence-id="${escapeAttribute(item.id)}">Godkänn koppling</button></div></article>`).join('')||'<p>Alla personrader är kopplade.</p>'}</div></section><section class="panel span12" style="margin-top:1rem"><p class="overrad">Båtidentiteter</p><h2>${boats.length} öppna förekomster</h2><p class="panelintro">Föreslagna båtar visas med all strukturerad metadata från Båtregistret utom bilder.</p><div class="reviewgrid">${boats.map(item=>boatReviewCard(item)).join('')||'<p>Alla båtförekomster är kopplade.</p>'}</div></section><section class="panel span12" style="margin-top:1rem"><p class="overrad">Efterkontroll</p><h2>${reviewed.length} manuella eller källgranskade båtkopplingar</h2><p class="panelintro">Här kan en redan gjord koppling granskas och ändras. Den gamla operationen finns kvar i historiken.</p><div class="reviewgrid">${reviewed.map(item=>boatReviewCard(item,true)).join('')||'<p>Inga manuella båtkopplingar ännu.</p>'}</div></section><section class="forandringsgrid" style="margin-top:1rem"><article class="forandringskolumn"><p class="overrad">Samma ID flera gånger</p><h3>Dubblettgrupper</h3><div class="dupletter">${duplicates.map(group=>`<div class="duplettrad"><b>${escapeHtml(releaseMoment(rMap.get(group.release_id)))} · ${escapeHtml(pMap.get(group.person_id)?.display_name||group.person_id)}</b><span>${group.items.map(item=>escapeHtml(item.person_name_raw)).join(' · ')}</span></div>`).join('')||'<p>Inga dubbletter.</p>'}</div></article><article class="forandringskolumn"><p class="overrad">Källvärde utan rättning</p><h3>Ogiltiga datum</h3>${dates.map(item=>`<div class="duplettrad"><b>${escapeHtml(item.birth_date_raw)}</b><span>${escapeHtml(releaseMoment(rMap.get(item.release_id)))} · ${escapeHtml(item.person_name_raw)}</span></div>`).join('')||'<p>Inga ogiltiga datum.</p>'}</article></section>`;
}

function render(){updateControls();app.innerHTML=({oversikt:renderOverview,utgava:renderEdition,matris:renderMatrix,forandringar:renderChanges,personer:renderPeople,granskning:renderReview}[ui.view]||renderOverview)();if($('#change-from')){$('#change-from').value=ui.from;$('#change-to').value=ui.to}}
async function confirmPerson(id){const select=document.querySelector(`[data-person-select="${CSS.escape(id)}"]`);if(!select?.value)return;await repository.setFields([{entityType:'person-occurrence',entityId:id,field:'person_id',value:select.value},{entityType:'person-occurrence',entityId:id,field:'match_status',value:'manuell'},{entityType:'person-occurrence',entityId:id,field:'match_method',value:'manuellt beslut i Klubbhistorik'},{entityType:'person-occurrence',entityId:id,field:'candidate_ids',value:[select.value]},{entityType:'person-occurrence',entityId:id,field:'confirmed',value:true}]);render();setStatus('Personkoppling sparad lokalt · Matrikel oförändrad','ok');syncNow().catch(()=>{})}
async function confirmBoat(id){const select=document.querySelector(`[data-boat-select="${CSS.escape(id)}"]`);if(!select?.value)return;await repository.setFields([{entityType:'boat-occurrence',entityId:id,field:'boat_id',value:select.value},{entityType:'boat-occurrence',entityId:id,field:'match_status',value:'manuell'},{entityType:'boat-occurrence',entityId:id,field:'match_method',value:'manuellt beslut i Klubbhistorik'},{entityType:'boat-occurrence',entityId:id,field:'candidate_ids',value:[select.value]},{entityType:'boat-occurrence',entityId:id,field:'confirmed',value:true}]);render();setStatus('Båtkoppling sparad lokalt · Båtregister oförändrat','ok');syncNow().catch(()=>{})}
function currentAudit(){return {exported_at:new Date().toISOString(),releases:releases().map(release=>({...release,coverage:coverage(release)})),counts:{source_rows:sourceRows().length,person_occurrences:personOccurrences().length,boat_occurrences:boatOccurrences().length,unresolved_people:unresolvedPeople().length,unresolved_boats:unresolvedBoats().length,duplicates:duplicateGroups().length,invalid_dates:invalidDates().length},unresolved_people:unresolvedPeople().map(item=>({id:item.id,release_id:item.release_id,raw:item.person_name_raw,candidates:item.candidate_ids})),unresolved_boats:unresolvedBoats().map(item=>({id:item.id,release_id:item.release_id,raw:item.boat_name_raw,candidates:item.candidate_ids})),duplicates:duplicateGroups().map(group=>({release_id:group.release_id,person_id:group.person_id,occurrence_ids:group.items.map(item=>item.id),raw_names:group.items.map(item=>item.person_name_raw)})),invalid_dates:invalidDates().map(item=>({id:item.id,raw:item.birth_date_raw}))}}
function exportAudit(){const blob=new Blob([JSON.stringify(currentAudit(),null,2)+'\n'],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`klubbhistorik-kontroll-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url)}

async function registerServiceWorker(){if(!('serviceWorker'in navigator)||location.protocol==='file:')return null;try{return await navigator.serviceWorker.register('./sw.js',{scope:'./'})}catch(error){console.warn('Appskalet kunde inte uppdateras',error);return null}}
async function completeOAuthCallbackIfNeeded(){const url=new URL(location.href);if(!url.searchParams.has('code')&&!url.searchParams.has('error'))return;const token=await completeDropboxOAuth();accessToken=token.access_token;accessTokenExpiresAt=Date.now()+Math.max(30,Number(token.expires_in||0)-60)*1000;if(token.refresh_token)await store.putMeta(TOKEN_META,token.refresh_token);for(const parameter of ['code','state','error','error_description'])url.searchParams.delete(parameter);history.replaceState({},'',`${url.pathname}${url.search}${url.hash}`)}
async function currentAccessToken(){if(accessToken&&Date.now()<accessTokenExpiresAt)return accessToken;const refreshToken=await store.getMeta(TOKEN_META);if(!refreshToken||!DROPBOX_CLIENT_ID||navigator.onLine===false)return null;const token=await exchangeDropboxRefreshToken({clientId:DROPBOX_CLIENT_ID,refreshToken});accessToken=token.access_token;accessTokenExpiresAt=Date.now()+Math.max(30,Number(token.expires_in||0)-60)*1000;if(token.refresh_token&&token.refresh_token!==refreshToken)await store.putMeta(TOKEN_META,token.refresh_token);return accessToken}
async function uploadBootstrapOps(transport){const pending=await store.getMeta(BOOTSTRAP_META);if(!pending?.pending)return 0;const deviceIds=new Set(pending.device_ids||[pending.device_id]);const operations=(await store.getAllOps()).filter(operation=>deviceIds.has(operation.device_id));const byDevice=new Map();for(const operation of operations){if(!byDevice.has(operation.device_id))byDevice.set(operation.device_id,[]);byDevice.get(operation.device_id).push(operation)}let uploaded=0;for(const deviceOperations of byDevice.values()){deviceOperations.sort((a,b)=>a.seq-b.seq);for(let index=0;index<deviceOperations.length;index+=250){const batch=createBatch(deviceOperations.slice(index,index+250));await transport.putBatch(batch);uploaded+=batch.ops.length}}await store.putMeta(BOOTSTRAP_META,{...pending,pending:false,uploaded_at:new Date().toISOString()});return uploaded}
async function syncNow(){if(syncPromise)return syncPromise;syncPromise=(async()=>{const hasCredential=Boolean(await store.getMeta(TOKEN_META));if(navigator.onLine===false){setStatus(`Offline · ${hasCredential?'Dropbox ansluten · ':''}historiken finns lokalt`,'warning');return null}const token=await currentAccessToken();if(!token){setStatus('Lokal pilotmaster · Dropbox ej ansluten','warning');connectButton.textContent='Anslut Dropbox';return null}connectButton.textContent='Synka Dropbox';setStatus('Synkar Klubbhistorik…');const transport=new DropboxTransport({accessToken:token,id:'dropbox-klubbhistorik',opsRoot:'/klubbhistorik/ops'});const bootstrap=await uploadBootstrapOps(transport);const result=await new SyncEngine({repository,transport}).syncOnce();render();setStatus(`Synkad · ${personOccurrences().length} medlemsrader · ${bootstrap+result.uploadedOps} upp, ${result.downloadedOps} ned`,'ok');return result})().catch(error=>{console.error(error);if(isOfflineError(error)){setStatus('Offline · lokal Klubbhistorik tillgänglig','warning');return null}setStatus(`Åtgärd krävs · ${error.message}`,'error');throw error}).finally(()=>{syncPromise=null});return syncPromise}
async function connectDropbox(){sessionStorage.setItem('korpholmen:oauth-return',new URL('klubbhistorik/',redirectUri()).pathname);const attempt=await beginDropboxOAuth({clientId:DROPBOX_CLIENT_ID,redirectUri:redirectUri(),scopes:DROPBOX_SCOPES});location.assign(attempt.url)}
async function bootstrapLocal(){if(!isSourceTree)throw new Error('Pilotmastern kan bara aktiveras från källappen');const responses=await Promise.all(LOCAL_BOOTSTRAP_URLS.map(url=>fetch(url,{cache:'no-store'})));const failed=responses.find(response=>!response.ok);if(failed)throw new Error(`Pilotmastern kunde inte läsas (${failed.status})`);const documents=await Promise.all(responses.map(response=>response.json()));if(documents.some(data=>data.operations_version!==1||!Array.isArray(data.operations)))throw new Error('Pilotmastern har fel format');const operations=documents.flatMap(data=>data.operations);operations.forEach(validateOperation);await repository.applyRemoteOps(operations);const deviceIds=[...new Set(documents.flatMap(data=>data.device_ids||[data.device_id]).filter(Boolean))];await store.putMeta(BOOTSTRAP_META,{pending:true,device_ids:deviceIds,migration_id:'klubbhistorik-full-master-2026-08-03',operations:operations.length});render();setStatus('Full källsäker master inläst lokalt · Matrikel och Båtregister är oförändrade','ok')}

document.addEventListener('click',event=>{const view=event.target.closest('[data-view]')?.dataset.view;if(view){ui.view=view;ui.personId=null;render();app.focus()}const release=event.target.closest('[data-open-release]')?.dataset.openRelease;if(release){ui.releaseId=release;ui.view='utgava';$('#release-filter').value=release;render()}const layer=event.target.closest('[data-layer]')?.dataset.layer;if(layer){ui.layer=layer;render()}const kind=event.target.closest('[data-kind]')?.dataset.kind;if(kind){ui.kind=kind;render()}const personId=event.target.closest('[data-person-id]')?.dataset.personId;if(personId){ui.personId=personId;ui.view='personer';render()}const action=event.target.closest('[data-action]')?.dataset.action;if(action==='back-people'){ui.personId=null;render()}if(action==='confirm-person')confirmPerson(event.target.closest('[data-occurrence-id]').dataset.occurrenceId).catch(error=>setStatus(error.message,'error'));if(action==='confirm-boat')confirmBoat(event.target.closest('[data-occurrence-id]').dataset.occurrenceId).catch(error=>setStatus(error.message,'error'))});
$('#global-search').addEventListener('input',event=>{ui.search=event.target.value;if(ui.view==='oversikt')ui.view='personer';render()});
$('#clear-search').addEventListener('click',()=>{ui.search='';$('#global-search').value='';render()});
$('#release-filter').addEventListener('change',event=>{ui.releaseId=event.target.value;ui.view='utgava';render()});
$('#export-audit').addEventListener('click',exportAudit);
connectButton.addEventListener('click',()=>currentAccessToken().then(token=>token?syncNow():connectDropbox()).catch(error=>setStatus(error.message,'error')));
bootstrapButton.addEventListener('click',()=>bootstrapLocal().catch(error=>setStatus(error.message,'error')));
app.addEventListener('change',event=>{if(event.target.id==='change-from'){ui.from=event.target.value;render()}if(event.target.id==='change-to'){ui.to=event.target.value;render()}if(event.target.matches('[data-boat-select]')){const preview=document.querySelector(`[data-boat-preview="${CSS.escape(event.target.dataset.boatSelect)}"]`);if(preview)preview.innerHTML=boatReferenceHtml(boatMap().get(event.target.value))}});
window.addEventListener('online',()=>syncNow().catch(()=>{}));window.addEventListener('offline',()=>syncNow().catch(()=>{}));

async function init(){const serviceWorkerPromise=registerServiceWorker();const db=await openSlaktlandskapDB({name:'kbk-klubbhistorik'});store=new IndexedDBStore(db);repository=await new Repository({store,deviceId:deviceId()}).init();bootstrapButton.hidden=!isSourceTree;const params=new URLSearchParams(location.search);if(params.has('person')){ui.view='personer';ui.personId=params.get('person')}if(params.has('release')){ui.view='utgava';ui.releaseId=params.get('release')}render();await completeOAuthCallbackIfNeeded();await syncNow();await serviceWorkerPromise}
init().catch(error=>{console.error(error);setStatus(`Kunde inte starta · ${error.message}`,'error')});
